const { test, expect } = require('@playwright/test')
const { E2E_USERNAME, E2E_PASSWORD, loginAsOwner } = require('./e2e-auth')
// @req FR-144 — actual browser login/approval and private device redemption.
// @spec SEC-025, SEC-001, SEC-008
async function begin(request, suffix) {
  const response=await request.post('/api/edge/pairing/start',{data:{deviceId:'EDGE-E2E-'+suffix,label:'เครื่องทดสอบ '+suffix}})
  expect(response.status()).toBe(200)
  return response.json()
}
test('phone approval returns after login and hands a scoped key only to Desktop', async ({page,request})=>{
  const start=await begin(request,'APPROVE')
  await page.setViewportSize({width:390,height:844})
  await page.goto(start.approvalUrl)
  await expect(page).toHaveURL(/\/login\?next=/)
  await page.getByLabel('Email or account code').fill(E2E_USERNAME)
  await page.getByLabel('Password',{exact:true}).fill(E2E_PASSWORD)
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page).toHaveURL(/\/edge\/pair$/)
  await expect(page.getByTestId('pairing-check-code')).toHaveText(start.checkCode)
  await page.getByLabel('ธุรกิจที่ต้องการเชื่อมต่อ').selectOption({index:1})
  await page.screenshot({path:'test-results/edge-pairing-mobile.png',fullPage:true})
  const approvalResponse=page.waitForResponse(response=>response.url().endsWith('/api/edge/pairing/approve') && response.request().postDataJSON()?.action==='approve')
  await page.getByRole('button',{name:'ยืนยันเชื่อมต่อเครื่องนี้'}).click()
  const approvalBody=await (await approvalResponse).json()
  await expect(page.getByRole('heading',{name:'ยืนยันการเชื่อมต่อแล้ว'})).toBeVisible()
  expect(JSON.stringify(approvalBody)).not.toContain('edgk_')
  expect(JSON.stringify(approvalBody)).not.toContain(start.deviceSecret)
  const wrong=await request.post('/api/edge/pairing/poll',{data:{requestId:start.requestId},headers:{authorization:'Bearer '+new URL(start.approvalUrl).hash.slice(1)}})
  expect(wrong.status()).toBe(410)
  const response=await request.post('/api/edge/pairing/poll',{data:{requestId:start.requestId},headers:{authorization:'Bearer '+start.deviceSecret}})
  expect(response.status()).toBe(200)
  const result=await response.json()
  expect(result.state).toBe('PAIRED')
  const heartbeat=await request.post('/api/agent/heartbeat',{
    data:{deviceId:result.pairing.deviceId,status:'unavailable'},
    headers:{authorization:'Bearer '+result.pairing.key},
  })
  expect(heartbeat.status()).toBe(200)
  expect((await heartbeat.json()).acknowledged).toBe(true)
  const repeated=await request.post('/api/edge/pairing/poll',{data:{requestId:start.requestId},headers:{authorization:'Bearer '+start.deviceSecret}})
  expect(repeated.status()).toBe(410)
})
test('browser can deny; the device receives no key',async({page,request})=>{
  await loginAsOwner(page)
  const start=await begin(request,'DENY')
  await page.goto(start.approvalUrl)
  await expect(page.getByTestId('pairing-check-code')).toHaveText(start.checkCode)
  await page.getByRole('button',{name:'ยกเลิก',exact:true}).click()
  await expect(page.getByText('ยกเลิกคำขอแล้ว ไม่มีการออกกุญแจให้เครื่องนี้')).toBeVisible()
  const response=await request.post('/api/edge/pairing/poll',{data:{requestId:start.requestId},headers:{authorization:'Bearer '+start.deviceSecret}})
  expect(await response.json()).toMatchObject({state:'DENIED'})
  await page.goto(start.approvalUrl)
  await expect(page.getByText('ยกเลิกคำขอแล้ว ไม่มีการออกกุญแจให้เครื่องนี้')).toBeVisible()
  expect(await page.evaluate(()=>sessionStorage.getItem('zuri.edge.pairing.approval'))).toBeNull()
})
