const { test, expect } = require('@playwright/test')
const { randomUUID } = require('node:crypto')
const { E2E_PASSWORD } = require('./e2e-auth')

// @req FR-241 — a signed-in person with no operator grant reads the programme plan
//   and the Domain map at /roadmap, without the Agent devices tab, while
//   /control/roadmap still refuses them.
// @spec ADR-092 D1–D3; ADR-048 D2
// @tested tests/e2e/fr241-roadmap-member-view.spec.js

test('a signed-in non-operator reads the roadmap preview and still cannot open the control board', async ({ page }, testInfo) => {
  const anonymous = await page.request.get('/roadmap', { maxRedirects: 0 })
  expect([307, 308]).toContain(anonymous.status())
  expect(anonymous.headers().location).toContain('/login')

  const signup = await page.request.post('/api/auth/signup', { data: {
    email: `fr241-${randomUUID()}@example.test`, displayName: 'FR-241 member', password: E2E_PASSWORD,
  } })
  expect(signup.status()).toBe(201)

  await page.goto('/roadmap')
  await expect(page.getByRole('heading', { name: 'Phases, sprints and tasks' })).toBeVisible()
  await expect(page.getByTestId('member-view-window')).toContainText('ไม่แสดงยอดการใช้งานแยกตามคนหรือเครื่อง')
  await expect(page.getByTestId('phase-metrics-PHASE-ZAI-01')).toContainText('sprint')
  await expect(page.getByRole('tab', { name: 'Domain map & inventory' })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Agent devices' })).toHaveCount(0)
  await expect(page.locator('[data-testid^="phase-people-"]')).toHaveCount(0)

  await page.goto('/roadmap?view=devices')
  await expect(page.getByRole('heading', { name: 'Phases, sprints and tasks' })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Agent devices' })).toHaveCount(0)

  await page.getByRole('tab', { name: 'Domain map & inventory' }).click()
  await expect(page).toHaveURL(/view=domains/)

  await testInfo.attach('roadmap-member-view', { body: await page.screenshot({ fullPage: false }), contentType: 'image/png' })

  const control = await page.goto('/control/roadmap')
  expect(control.status()).toBe(404)
})

test('the member roadmap remains operable at 390px and 430px without page overflow', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const signup = await page.request.post('/api/auth/signup', { data: {
    email: `fr241-mobile-${randomUUID()}@example.test`, displayName: 'FR-241 mobile member', password: E2E_PASSWORD,
  } })
  expect(signup.status()).toBe(201)

  await page.goto('/roadmap')
  await expect(page.getByTestId('roadmap-evidence')).toBeVisible()
  // SUBPLAN-KI-PRODUCTION-ACTIVATION's implementationState moved NOT_STARTED -> IN_PROGRESS
  // in roadmap-sot.js (generated by scripts/programme-containers.mjs) on 2026-09-24, commit
  // 366eb717 "regenerate roadmap-sot to match TASK-ZAI-050 reconciliation": production
  // observation recorded the ki17 overlay and genesis-worker running since 2026-09-21 with
  // 22 published generations. The generated data is canonical and correct; this assertion
  // was not updated to match it.
  await expect(page.getByTestId('production-activation-gate')).toContainText('IN PROGRESS')
  await expect(page.locator('[data-testid^="genesisrag17-stage-"]')).toHaveCount(17)
  await expect(page.getByRole('tab', { name: 'Agent devices' })).toHaveCount(0)

  const pageOverflow = () => page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  expect(await pageOverflow()).toBeLessThanOrEqual(1)

  const phase = page.getByRole('button', { name: /PHASE-ZAI-01/ }).first()
  await expect(phase).toHaveAttribute('aria-expanded', 'true')
  await expect(phase).toHaveAttribute('aria-controls', 'phase-detail-PHASE-ZAI-01')
  await phase.focus()
  await expect(phase).toBeFocused()
  const phaseBox = await phase.boundingBox()
  expect(phaseBox).not.toBeNull()
  expect(phaseBox.height).toBeGreaterThanOrEqual(44)

  await phase.click()
  await expect(phase).toHaveAttribute('aria-expanded', 'false')
  await phase.click()
  await expect(phase).toHaveAttribute('aria-expanded', 'true')

  const task = page.locator('#task-TASK-ZAI-001').getByRole('button').first()
  await expect(task).toHaveAttribute('aria-expanded', 'false')
  await expect(task).toHaveAttribute('aria-controls', 'task-detail-TASK-ZAI-001')
  await task.focus()
  await expect(task).toBeFocused()
  const taskBox = await task.boundingBox()
  expect(taskBox).not.toBeNull()
  expect(taskBox.height).toBeGreaterThanOrEqual(44)
  await task.click()
  await expect(task).toHaveAttribute('aria-expanded', 'true')

  const chart = await page.getByTestId('roadmap-history-chart').evaluate((element) => ({
    clientWidth: element.clientWidth,
    scrollWidth: element.scrollWidth,
  }))
  expect(chart.scrollWidth).toBeGreaterThan(chart.clientWidth)
  const metrics = await page.getByTestId('phase-metrics-frame-PHASE-ZAI-01').evaluate((element) => ({
    clientWidth: element.clientWidth,
    scrollWidth: element.scrollWidth,
  }))
  expect(metrics.scrollWidth).toBeGreaterThan(metrics.clientWidth)
  expect(await pageOverflow()).toBeLessThanOrEqual(1)

  await page.getByRole('tab', { name: 'Domain map & inventory' }).click()
  await expect(page).toHaveURL(/view=domains/)
  await expect(page.getByTestId('domain-map-view')).toBeVisible()
  await expect(page.getByTestId('production-activation-gate')).toHaveCount(0)
  expect(await pageOverflow()).toBeLessThanOrEqual(1)

  await page.setViewportSize({ width: 430, height: 932 })
  await expect(page.getByTestId('domain-map-view')).toBeVisible()
  expect(await pageOverflow()).toBeLessThanOrEqual(1)

  await testInfo.attach('roadmap-member-mobile', { body: await page.screenshot({ fullPage: false }), contentType: 'image/png' })
})
