// @req FR-105 — canonical delivery status, proof scope and implementation state
// projected from docs/roadmap/ROADMAP.md. The 24-week document is not a second
// status source; it supplies the compatibility topology and Task Containers.
// @spec ADR-048 D3, ADR-086 D3
// @tested tests/unit/programme-containers.test.js
//
// GENERATED by scripts/programme-containers.mjs. Do not hand-edit.
export const ROADMAP_SOT = {
  "schemaVersion": 1,
  "statusVocabulary": [
    "planned",
    "in-progress",
    "review",
    "done",
    "blocked"
  ],
  "proofScopeVocabulary": [
    "SPEC",
    "UNKNOWN",
    "LOCAL",
    "ISOLATED",
    "HOSTED_CI",
    "PRODUCTION"
  ],
  "implementationStateVocabulary": [
    "NOT_STARTED",
    "IN_PROGRESS",
    "LOCAL",
    "ISOLATED_ACCEPTED",
    "MERGED",
    "DEPLOYED",
    "ACTIVE",
    "BLOCKED",
    "UNKNOWN"
  ],
  "programme": {
    "phases": {
      "PHASE-ZAI-01": {
        "status": "in-progress",
        "progress": 91
      },
      "PHASE-ZAI-02": {
        "status": "in-progress",
        "progress": 48
      },
      "PHASE-ZAI-03": {
        "status": "in-progress",
        "progress": 10
      },
      "PHASE-ZAI-04": {
        "status": "planned",
        "progress": 0
      },
      "PHASE-ZAI-05": {
        "status": "in-progress",
        "progress": 17
      },
      "PHASE-ZAI-06": {
        "status": "planned",
        "progress": 0
      }
    },
    "sprints": {
      "SPR-ZAI-01": {
        "status": "in-progress",
        "progress": 93
      },
      "SPR-ZAI-02": {
        "status": "in-progress",
        "progress": 91
      },
      "SPR-ZAI-03": {
        "status": "in-progress",
        "progress": 40
      },
      "SPR-ZAI-04": {
        "status": "in-progress",
        "progress": 19
      },
      "SPR-ZAI-05": {
        "status": "in-progress",
        "progress": 21
      },
      "SPR-ZAI-06": {
        "status": "in-progress",
        "progress": 4
      },
      "SPR-ZAI-07": {
        "status": "planned",
        "progress": 0
      },
      "SPR-ZAI-08": {
        "status": "planned",
        "progress": 0
      },
      "SPR-ZAI-09": {
        "status": "in-progress",
        "progress": 50
      },
      "SPR-ZAI-10": {
        "status": "planned",
        "progress": 0
      },
      "SPR-ZAI-11": {
        "status": "planned",
        "progress": 0
      },
      "SPR-ZAI-12": {
        "status": "planned",
        "progress": 0
      }
    }
  },
  "dag": {
    "algorithm": "kahn-topological-layers",
    "nodeCount": 120,
    "edgeCount": 134,
    "waveCount": 21,
    "missingDependencies": [],
    "cycles": [],
    "parallelPolicy": "same-wave tasks have no declared dependency path; run them in parallel only after lane, ownership and shared-file conflict checks pass",
    "waves": [
      {
        "wave": 1,
        "taskIds": [
          "TASK-ZAI-001",
          "TASK-ZAI-002",
          "TASK-ZAI-005",
          "TASK-ZAI-006",
          "TASK-ZAI-031",
          "TASK-ZAI-032",
          "TASK-ZAI-035",
          "TASK-ZAI-036",
          "TASK-ZAI-040",
          "TASK-ZAI-060",
          "TASK-ZAI-064",
          "TASK-ZAI-076",
          "TASK-ZAI-116"
        ]
      },
      {
        "wave": 2,
        "taskIds": [
          "TASK-ZAI-003",
          "TASK-ZAI-007",
          "TASK-ZAI-017",
          "TASK-ZAI-033",
          "TASK-ZAI-034",
          "TASK-ZAI-037",
          "TASK-ZAI-041",
          "TASK-ZAI-045",
          "TASK-ZAI-061",
          "TASK-ZAI-065",
          "TASK-ZAI-066",
          "TASK-ZAI-068",
          "TASK-ZAI-077",
          "TASK-ZAI-117",
          "TASK-ZAI-118",
          "TASK-ZAI-119"
        ]
      },
      {
        "wave": 3,
        "taskIds": [
          "TASK-ZAI-004",
          "TASK-ZAI-008",
          "TASK-ZAI-009",
          "TASK-ZAI-010",
          "TASK-ZAI-038",
          "TASK-ZAI-046",
          "TASK-ZAI-047",
          "TASK-ZAI-049",
          "TASK-ZAI-062",
          "TASK-ZAI-067"
        ]
      },
      {
        "wave": 4,
        "taskIds": [
          "TASK-ZAI-011",
          "TASK-ZAI-012",
          "TASK-ZAI-013",
          "TASK-ZAI-018",
          "TASK-ZAI-024",
          "TASK-ZAI-039",
          "TASK-ZAI-048",
          "TASK-ZAI-050",
          "TASK-ZAI-052",
          "TASK-ZAI-063",
          "TASK-ZAI-069"
        ]
      },
      {
        "wave": 5,
        "taskIds": [
          "TASK-ZAI-014",
          "TASK-ZAI-019",
          "TASK-ZAI-025",
          "TASK-ZAI-026",
          "TASK-ZAI-028",
          "TASK-ZAI-043",
          "TASK-ZAI-051",
          "TASK-ZAI-053",
          "TASK-ZAI-055",
          "TASK-ZAI-070"
        ]
      },
      {
        "wave": 6,
        "taskIds": [
          "TASK-ZAI-015",
          "TASK-ZAI-016",
          "TASK-ZAI-020",
          "TASK-ZAI-021",
          "TASK-ZAI-027",
          "TASK-ZAI-029",
          "TASK-ZAI-042",
          "TASK-ZAI-044",
          "TASK-ZAI-054",
          "TASK-ZAI-071"
        ]
      },
      {
        "wave": 7,
        "taskIds": [
          "TASK-ZAI-022",
          "TASK-ZAI-030",
          "TASK-ZAI-056",
          "TASK-ZAI-059",
          "TASK-ZAI-072"
        ]
      },
      {
        "wave": 8,
        "taskIds": [
          "TASK-ZAI-023",
          "TASK-ZAI-057",
          "TASK-ZAI-073",
          "TASK-ZAI-074"
        ]
      },
      {
        "wave": 9,
        "taskIds": [
          "TASK-ZAI-058",
          "TASK-ZAI-075"
        ]
      },
      {
        "wave": 10,
        "taskIds": [
          "TASK-ZAI-078",
          "TASK-ZAI-088",
          "TASK-ZAI-104"
        ]
      },
      {
        "wave": 11,
        "taskIds": [
          "TASK-ZAI-079",
          "TASK-ZAI-080",
          "TASK-ZAI-089",
          "TASK-ZAI-090",
          "TASK-ZAI-092"
        ]
      },
      {
        "wave": 12,
        "taskIds": [
          "TASK-ZAI-081",
          "TASK-ZAI-091",
          "TASK-ZAI-093",
          "TASK-ZAI-100"
        ]
      },
      {
        "wave": 13,
        "taskIds": [
          "TASK-ZAI-082",
          "TASK-ZAI-094",
          "TASK-ZAI-096",
          "TASK-ZAI-097",
          "TASK-ZAI-105"
        ]
      },
      {
        "wave": 14,
        "taskIds": [
          "TASK-ZAI-083",
          "TASK-ZAI-095",
          "TASK-ZAI-098",
          "TASK-ZAI-099",
          "TASK-ZAI-101",
          "TASK-ZAI-106",
          "TASK-ZAI-109"
        ]
      },
      {
        "wave": 15,
        "taskIds": [
          "TASK-ZAI-084",
          "TASK-ZAI-102",
          "TASK-ZAI-107",
          "TASK-ZAI-110"
        ]
      },
      {
        "wave": 16,
        "taskIds": [
          "TASK-ZAI-085",
          "TASK-ZAI-108"
        ]
      },
      {
        "wave": 17,
        "taskIds": [
          "TASK-ZAI-086",
          "TASK-ZAI-103",
          "TASK-ZAI-111"
        ]
      },
      {
        "wave": 18,
        "taskIds": [
          "TASK-ZAI-087",
          "TASK-ZAI-112",
          "TASK-ZAI-120"
        ]
      },
      {
        "wave": 19,
        "taskIds": [
          "TASK-ZAI-113"
        ]
      },
      {
        "wave": 20,
        "taskIds": [
          "TASK-ZAI-114"
        ]
      },
      {
        "wave": 21,
        "taskIds": [
          "TASK-ZAI-115"
        ]
      }
    ]
  },
  "subplans": [
    {
      "id": "SUBPLAN-KI-17STAGE",
      "parent": "FEAT-013 / FR-109..119",
      "status": "in-progress",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-SPEC.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "KI-17-STAGE",
      "relation": "primary; production activation is separate"
    },
    {
      "id": "SUBPLAN-KI-ADMISSION",
      "parent": "FR-173 / ADR-072",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "KI-ADMISSION",
      "relation": "primary"
    },
    {
      "id": "SUBPLAN-KI-PRODUCTION-ACTIVATION",
      "parent": "TASK-ZAI-050 / ADR-073 amendment / ADR-075 Phase 2",
      "status": "planned",
      "proofScope": "SPEC",
      "implementationState": "NOT_STARTED",
      "authority": "docs/decisions/ADR-073-GENESISRAG17-ISOLATED-EXECUTION-AND-PUBLICATION.md",
      "evidence": "ADR-075 Phase 2 gate; no production activation claim",
      "duplicateKey": "KI-PRODUCTION-ACTIVATION",
      "relation": "gate; do not infer from isolated acceptance"
    },
    {
      "id": "SUBPLAN-SMARTGIFT-STRUCTURED-ADAPTER",
      "parent": "TASK-ZAI-042 / FR-187..189 / ADR-075",
      "status": "review",
      "proofScope": "LOCAL",
      "implementationState": "LOCAL",
      "authority": "docs/decisions/ADR-075-SMARTGIFT-CATALOG-ENTERS-VIA-17-STAGE-SOURCE-ADAPTER.md",
      "evidence": "TASK-FR-187 local tests; four-process acceptance still open",
      "duplicateKey": "KI-CATALOG-PUBLISH",
      "relation": "adapter; replaces legacy direct catalog writer after rollout"
    },
    {
      "id": "SUBPLAN-SMARTGIFT-DIRECT-WRITER",
      "parent": "TASK-ZAI-042 / ADR-075 architecture baseline",
      "status": "review",
      "proofScope": "UNKNOWN",
      "implementationState": "UNKNOWN",
      "authority": "docs/decisions/ADR-075-SMARTGIFT-CATALOG-ENTERS-VIA-17-STAGE-SOURCE-ADAPTER.md",
      "evidence": "legacy direct writer; production status requires a separate live check",
      "duplicateKey": "KI-CATALOG-PUBLISH",
      "relation": "legacy/fallback; never a second canonical writer"
    },
    {
      "id": "SUBPLAN-ROADMAP-MOBILE",
      "parent": "FR-105 / FR-241 / ADR-092",
      "status": "planned",
      "proofScope": "SPEC",
      "implementationState": "NOT_STARTED",
      "authority": "ROADMAP.md#canonical-delivery-ledger",
      "evidence": "mobile design approved for separate-branch implementation; no mobile viewport evidence yet",
      "duplicateKey": "PLATFORM-ROADMAP-UI",
      "relation": "responsive adaptation; one board and one SOT, not a second roadmap",
      "scope": [
        "Keep /roadmap member and /control/roadmap operator routes and their existing server-side privacy boundary",
        "Use the same ROADMAP.md and roadmap-sot.js data; do not create a mobile-only status source",
        "Make programme/domain tabs, phase and task accordions, SOT/proof chips, GenesisRAG17 coverage, deliverables and gates usable at 360–430 CSS px",
        "Keep status, proof scope and implementation state visually distinct; show isolated acceptance separately from production activation",
        "Add mobile E2E evidence at 390x844 for no page overflow, touch hit targets, accordion state, route access and member/operator data boundaries"
      ],
      "acceptance": [
        "The member route is readable and operable at 390x844 and 430x932 without document-level horizontal overflow",
        "Phase/task controls have touch-sized hit areas and preserve keyboard focus and aria-expanded semantics",
        "Charts and dense metrics scroll only inside their bounded frame; the page itself does not scroll horizontally",
        "Member view keeps Domain map but never exposes Agent devices, person/device breakdowns, tool names or model names",
        "The mobile view exposes the 17-stage GenesisRAG17 coverage and the production-activation planned gate without upgrading isolated proof",
        "Focused mobile E2E, targeted unit tests, build and governance pass"
      ],
      "handoff": "Implementation is delegated to a separate agent worktree after this SOT plan is committed; branch and commit evidence are recorded only after delivery."
    }
  ],
  "coverage": [
    {
      "stageId": "DPS-KI-INGEST",
      "stage": "Stage 1",
      "owner": "zuri-ai / Tier 1",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-INGEST",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-PARSE",
      "stage": "Stage 2",
      "owner": "zuri-ai / Tier 1",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-PARSE",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-PROVENANCE",
      "stage": "Stage 3",
      "owner": "zuri-ai / Tier 1",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-PROVENANCE",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-NORMALIZE",
      "stage": "Stage 4",
      "owner": "zuri-ai / Tier 1",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-NORMALIZE",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-CLASSIFY",
      "stage": "Stage 5",
      "owner": "zuri-ai / Tier 1",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-CLASSIFY",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-DEDUPE",
      "stage": "Stage 6",
      "owner": "zuri-ai / Tier 1",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-DEDUPE",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-CHUNK",
      "stage": "Stage 7",
      "owner": "zuri-ai / Tier 1",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-CHUNK",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-ENTITY-EXTRACT",
      "stage": "Stage 8",
      "owner": "zuri-ai / Tier 1",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-ENTITY-EXTRACT",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-ENTITY-RESOLVE",
      "stage": "Stage 9",
      "owner": "GKS / Tier 3",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-ENTITY-RESOLVE",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-FACT-EXTRACT",
      "stage": "Stage 10",
      "owner": "GKS / Tier 3",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-FACT-EXTRACT",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-ONTOLOGY-MAP",
      "stage": "Stage 11",
      "owner": "GKS / Tier 3",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-ONTOLOGY-MAP",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-TEMPORAL-MAP",
      "stage": "Stage 12",
      "owner": "GKS / Tier 3",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-TEMPORAL-MAP",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-GRAPH-BUILD",
      "stage": "Stage 13",
      "owner": "GKS decision + GenesisBlock worker execution",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-GRAPH-BUILD",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-ENRICH",
      "stage": "Stage 14",
      "owner": "GKS / Tier 3",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-ENRICH",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-EMBED",
      "stage": "Stage 15",
      "owner": "GenesisBlock worker / Tier 4",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-EMBED",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-INDEX",
      "stage": "Stage 16",
      "owner": "GenesisBlock worker / Tier 4",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-INDEX",
      "relation": "primary; production activation remains a separate subplan"
    },
    {
      "stageId": "DPS-KI-QUALITY-GATE",
      "stage": "Stage 17",
      "owner": "GKS quality gate + GenesisBlock publication",
      "status": "done",
      "proofScope": "ISOLATED",
      "implementationState": "ISOLATED_ACCEPTED",
      "authority": "docs/KNOWLEDGE-INGESTION-17-STAGE-FLOW.md",
      "evidence": ".brain/reports/GENESISRAG17-ACCEPTANCE.md",
      "duplicateKey": "DPS-KI-QUALITY-GATE",
      "relation": "primary; production activation remains a separate subplan"
    }
  ]
}

export const ROADMAP_TASK_LEDGER = [
  {
    "id": "TASK-ZAI-001",
    "sprint": "SPR-ZAI-01",
    "title": "Close the production request-session and credential boundary",
    "status": "review",
    "proofScope": "UNKNOWN",
    "implementationState": "IN_PROGRESS",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 10; FEAT-010; .brain/reports/2026-09-20-task-zai-001-closeout.md"
  },
  {
    "id": "TASK-ZAI-002",
    "sprint": "SPR-ZAI-01",
    "title": "Declare the five built-but-undeclared features into the registry",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3 evidence baseline"
  },
  {
    "id": "TASK-ZAI-003",
    "sprint": "SPR-ZAI-01",
    "title": "Profile-first onboarding and Waiting Room, FR-066",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-001",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; PRD FR-066, FR-122"
  },
  {
    "id": "TASK-ZAI-004",
    "sprint": "SPR-ZAI-02",
    "title": "Workspace collaboration boundary and scoped invites, FR-067",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-003",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; PRD FR-067; FR-195 generalises it"
  },
  {
    "id": "TASK-ZAI-005",
    "sprint": "SPR-ZAI-02",
    "title": "Supabase data pipeline monitor and replay, FR-071",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; PRD FR-071"
  },
  {
    "id": "TASK-ZAI-006",
    "sprint": "SPR-ZAI-02",
    "title": "Write the governed memory read and write contract",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 4; ADR-050, ADR-063, ADR-067, ADR-068, ADR-072"
  },
  {
    "id": "TASK-ZAI-007",
    "sprint": "SPR-ZAI-03",
    "title": "Agent Role registry with five core roles",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-006",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 5"
  },
  {
    "id": "TASK-ZAI-008",
    "sprint": "SPR-ZAI-03",
    "title": "Role-scoped memory partition and retrieval policy",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-007",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 rows 4 and 5"
  },
  {
    "id": "TASK-ZAI-009",
    "sprint": "SPR-ZAI-03",
    "title": "Agent Factory, the standard business agent template",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-007",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Proposal scope, AI Control"
  },
  {
    "id": "TASK-ZAI-010",
    "sprint": "SPR-ZAI-04",
    "title": "Approval Gateway L1 to L4 over the FR-026 action gate",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-007",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 9"
  },
  {
    "id": "TASK-ZAI-011",
    "sprint": "SPR-ZAI-04",
    "title": "Verification and notification fabric on approval outcomes",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-010",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 9"
  },
  {
    "id": "TASK-ZAI-012",
    "sprint": "SPR-ZAI-04",
    "title": "Mission feed: agent missions and their approvals surface as Development-domain work in the Project system",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-010",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 2; FR-040, FR-063, FR-068, FR-108"
  },
  {
    "id": "TASK-ZAI-013",
    "sprint": "SPR-ZAI-05",
    "title": "Standard Business Template and provisioning path",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-009",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 6"
  },
  {
    "id": "TASK-ZAI-014",
    "sprint": "SPR-ZAI-05",
    "title": "Onboard Business number two end to end under isolation",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-013",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 6"
  },
  {
    "id": "TASK-ZAI-015",
    "sprint": "SPR-ZAI-05",
    "title": "Per-business visibility regression at two-business scale",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-014",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; FEATURE-MAP FR-061 and FR-062"
  },
  {
    "id": "TASK-ZAI-016",
    "sprint": "SPR-ZAI-06",
    "title": "Cross-business governed analytics read model",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-014",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 6"
  },
  {
    "id": "TASK-ZAI-017",
    "sprint": "SPR-ZAI-06",
    "title": "Connector number two under the FR-081 ingestion boundary — FlowAccount read-only pull, FR-125",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-005",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 8; ADR-053"
  },
  {
    "id": "TASK-ZAI-018",
    "sprint": "SPR-ZAI-06",
    "title": "Automation workflows one and two end to end",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-010; TASK-ZAI-017",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 7"
  },
  {
    "id": "TASK-ZAI-019",
    "sprint": "SPR-ZAI-07",
    "title": "Visual Office 2.5D scene model and shell",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-012",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 1"
  },
  {
    "id": "TASK-ZAI-020",
    "sprint": "SPR-ZAI-07",
    "title": "Bind Business, Agent, Mission and Approval objects to live reads",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-019",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 1"
  },
  {
    "id": "TASK-ZAI-021",
    "sprint": "SPR-ZAI-07",
    "title": "Accessibility and reduced-motion contract for the 2.5D surface",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-019",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; UI-DESIGN-SYSTEM section 3"
  },
  {
    "id": "TASK-ZAI-022",
    "sprint": "SPR-ZAI-08",
    "title": "Live agent activity presence and mission tracking in-scene",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-020",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Proposal scope, Business Layer"
  },
  {
    "id": "TASK-ZAI-023",
    "sprint": "SPR-ZAI-08",
    "title": "Surface the L1 to L4 approval queue inside Visual Office",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-011; TASK-ZAI-022",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 rows 1 and 9"
  },
  {
    "id": "TASK-ZAI-024",
    "sprint": "SPR-ZAI-09",
    "title": "Second Brain retrieval by Business, Role and Permission",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-008",
    "authority": "ROADMAP.md",
    "evidence": "PR #481 merged at `823ae325`; hosted verify/govern/tests/build/edge/changes passed; production NOT_RUN; FR-098, FR-173, ADR-072"
  },
  {
    "id": "TASK-ZAI-025",
    "sprint": "SPR-ZAI-09",
    "title": "Memory lineage, replay and the no-silent-replay guarantee",
    "status": "review",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-024",
    "authority": "ROADMAP.md",
    "evidence": "PR #494 implementation head `a2bd5f90` merged at `06d61da5`; hosted Governance run #1381 govern/tests/build/verify/changes passed with E2E skipped; Edge run #711 edge-verify/changes passed with desktop skipped; local focused 52 tests, govern and build passed; production, owner activation, MSP, GKS, migrations, deployment and credentials remain NOT_RUN; broader task criteria remain open"
  },
  {
    "id": "TASK-ZAI-026",
    "sprint": "SPR-ZAI-10",
    "title": "Interactive Node View 3D over the governed relation graph",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-024",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 3"
  },
  {
    "id": "TASK-ZAI-027",
    "sprint": "SPR-ZAI-10",
    "title": "Structure and edge direct manipulation with handoff contracts",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-026",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; FEATURE-MAP FR-082 to FR-085"
  },
  {
    "id": "TASK-ZAI-028",
    "sprint": "SPR-ZAI-10",
    "title": "Automation workflows three to five and connector number three",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-018",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 rows 7 and 8"
  },
  {
    "id": "TASK-ZAI-029",
    "sprint": "SPR-ZAI-11",
    "title": "Integration hardening plus load and security test campaign",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-028",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 10"
  },
  {
    "id": "TASK-ZAI-030",
    "sprint": "SPR-ZAI-12",
    "title": "UAT, deployment, data and security checklist, training and handover",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-029",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 10"
  },
  {
    "id": "TASK-ZAI-031",
    "sprint": "SPR-ZAI-01",
    "title": "Inventory catalogue, stock ledger, recipes and product natures — FEAT-020, FR-154 to FR-156, FR-168",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; CR-019 deliverable 11; ADR-024"
  },
  {
    "id": "TASK-ZAI-032",
    "sprint": "SPR-ZAI-01",
    "title": "Sales tasks in CRM — FEAT-022, FR-161",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; CR-019 deliverable 11; ADR-064"
  },
  {
    "id": "TASK-ZAI-033",
    "sprint": "SPR-ZAI-01",
    "title": "Commerce orders and payments — FEAT-023, FR-166, FR-163",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-031",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; CR-019 deliverable 11; ADR-065"
  },
  {
    "id": "TASK-ZAI-034",
    "sprint": "SPR-ZAI-01",
    "title": "Procurement suppliers, purchase orders and goods receipts — FEAT-024, FR-164, FR-165",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-031",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; CR-019 deliverable 11; ADR-066"
  },
  {
    "id": "TASK-ZAI-035",
    "sprint": "SPR-ZAI-01",
    "title": "Asset Management foundation, evidence intake and edge extraction — FEAT-015 to FEAT-017, FR-133 to FR-144",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; CR-019 deliverable 11; ADR-055, ADR-056, ADR-059"
  },
  {
    "id": "TASK-ZAI-036",
    "sprint": "SPR-ZAI-01",
    "title": "LINE OA Studio multi-account, rich menu, LIFF and server-owned transport — FEAT-018, FEAT-019, FR-146 to FR-153, FR-190",
    "status": "review",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "PR #480 merged at `d8a8e0e`; hosted checks passed; provider canary, real LINE delivery and production remain NOT_RUN"
  },
  {
    "id": "TASK-ZAI-037",
    "sprint": "SPR-ZAI-02",
    "title": "SCM and CRM parent navigation, Business capabilities and module tabs — FR-167, FR-169, FR-170, FR-172",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-031",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; CR-019 deliverable 11; ADR-069, ADR-071"
  },
  {
    "id": "TASK-ZAI-038",
    "sprint": "SPR-ZAI-02",
    "title": "SmartGift SCM located ledger, landed cost, work orders, ATP and agent tools — FEAT-025, FR-174 to FR-182",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-031; TASK-ZAI-034",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; CR-019 deliverable 11; ADR-074"
  },
  {
    "id": "TASK-ZAI-039",
    "sprint": "SPR-ZAI-02",
    "title": "Commerce billing documents, POS checkout and physical stocktake — FR-186, FR-183, FR-184",
    "status": "review",
    "proofScope": "UNKNOWN",
    "implementationState": "IN_PROGRESS",
    "dependsOn": "TASK-ZAI-033; TASK-ZAI-038",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; CR-019 deliverable 11; ZAI-PROPOSAL-COMMERCE-BILLING-POS-20260910"
  },
  {
    "id": "TASK-ZAI-040",
    "sprint": "SPR-ZAI-02",
    "title": "Marketing strategy, campaigns, content, operations and broadcast planning — FEAT-021, FR-157 to FR-160, FR-162, FR-185",
    "status": "review",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "PR #482 merged at `11826890`; hosted checks passed; target, provider, owner, release and production gates remain open"
  },
  {
    "id": "TASK-ZAI-041",
    "sprint": "SPR-ZAI-02",
    "title": "Identity lifecycle: withdrawable grants, Employment and LegalEntity, invites and segregation of duties, audit access evidence — FEAT-027 to FEAT-030, FR-191 to FR-199",
    "status": "review",
    "proofScope": "UNKNOWN",
    "implementationState": "IN_PROGRESS",
    "dependsOn": "TASK-ZAI-001",
    "authority": "ROADMAP.md",
    "evidence": "cited E2E failure; no all-CI-pass claim; production migration and owner approval/activation remain NOT_RUN; 24-week baseline; Section 3.1 rows 9 and 10; ADR-077 to ADR-080"
  },
  {
    "id": "TASK-ZAI-042",
    "sprint": "SPR-ZAI-02",
    "title": "SmartGift catalog convergence through the seventeen-stage adapter — FEAT-026, FR-187 to FR-189",
    "status": "in-progress",
    "proofScope": "UNKNOWN",
    "implementationState": "IN_PROGRESS",
    "dependsOn": "TASK-ZAI-025",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 4; ADR-075"
  },
  {
    "id": "TASK-ZAI-043",
    "sprint": "SPR-ZAI-03",
    "title": "Apply every pending deliverable-11 migration on production and record it in the migration notes",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-038; TASK-ZAI-039; TASK-ZAI-040; TASK-ZAI-041",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; GATE-ZAI-09; ADR-057"
  },
  {
    "id": "TASK-ZAI-044",
    "sprint": "SPR-ZAI-06",
    "title": "GATE-ZAI-09 evidence run: ERP modules accepted on production for Business one",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-043",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; GATE-ZAI-09"
  },
  {
    "id": "TASK-ZAI-045",
    "sprint": "SPR-ZAI-02",
    "title": "Knowledge file intake: Text/Markdown and FileAsset admission into an immutable raw artifact at Stage 1 — FR-173, FR-081, FR-109",
    "status": "review",
    "proofScope": "UNKNOWN",
    "implementationState": "IN_PROGRESS",
    "dependsOn": "TASK-ZAI-005",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 4; ADR-072, ADR-073"
  },
  {
    "id": "TASK-ZAI-046",
    "sprint": "SPR-ZAI-02",
    "title": "Tier 1 stage calculators, composition and quarantine, Stage 2 to 8 — FR-111 to FR-119",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-045",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 4; ADR-050"
  },
  {
    "id": "TASK-ZAI-047",
    "sprint": "SPR-ZAI-03",
    "title": "Knowledge base console: source library, ingestion run status, corpus and generation registry, cited query",
    "status": "review",
    "proofScope": "ISOLATED",
    "implementationState": "ISOLATED_ACCEPTED",
    "dependsOn": "TASK-ZAI-045",
    "authority": "ROADMAP.md",
    "evidence": "frozen production-base branch; isolated implementation/native acceptance; runtime activation under TASK-ZAI-050; not deployed; ../plans/TASK-ZAI-047-KNOWLEDGE-CONSOLE.md"
  },
  {
    "id": "TASK-ZAI-048",
    "sprint": "SPR-ZAI-03",
    "title": "Binary document parsing at Stage 2 (PDF, DOCX, HTML, tables, OCR) with raw mapping at Stage 3 and offsets at Stage 7 to 9",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-046",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; 17-stage flow, \"PDF/OCR/HTML/table parser\" row; FR-115, FR-138"
  },
  {
    "id": "TASK-ZAI-049",
    "sprint": "SPR-ZAI-03",
    "title": "Durable file storage, retention and recoverability for knowledge raw artifacts on production (spec §3.1)",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-045",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; Section 3.1 row 4; FR-045, FR-111, FR-137"
  },
  {
    "id": "TASK-ZAI-050",
    "sprint": "SPR-ZAI-03",
    "title": "Activate the seventeen-stage runtime on production beyond the isolated profile: knowledge migrations recorded, MSP/GKS/worker reachable, one real corpus published",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-045; TASK-ZAI-049",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; ADR-073 amendment; ADR-075 Phase 2 gate"
  },
  {
    "id": "TASK-ZAI-051",
    "sprint": "SPR-ZAI-03",
    "title": "Multi-source concurrency, scheduler and replay surface over the FR-081 ingestion boundary",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-050",
    "authority": "ROADMAP.md",
    "evidence": "24-week baseline; 17-stage flow, \"connector/แหล่งเอกสาร\" row; FR-081"
  },
  {
    "id": "TASK-ZAI-052",
    "sprint": "SPR-ZAI-02",
    "title": "Cost and quote engine decision record — proposal, ADR, FR and FEAT declarations with the owner's nine decisions",
    "status": "done",
    "proofScope": "SPEC",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-038",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../change-requests/ZAI-PROPOSAL-SMARTGIFT-COST-QUOTE-ENGINE-20260913.md"
  },
  {
    "id": "TASK-ZAI-053",
    "sprint": "SPR-ZAI-02",
    "title": "Supplier cost sheets — factory cost intake with locked FX, confirmed SKU mapping and carton attributes (Procurement, Inventory)",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-052; TASK-ZAI-034",
    "authority": "ROADMAP.md",
    "evidence": "PR #483 merged at `68d27022` after the strict Phase-B inventory fix; hosted checks passed; production migration/activation NOT_RUN"
  },
  {
    "id": "TASK-ZAI-054",
    "sprint": "SPR-ZAI-02",
    "title": "Goods receipts post the landed unit cost to the stock ledger, and the SKU page gains a cost card",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-053; TASK-ZAI-038",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../change-requests/ZAI-PROPOSAL-SMARTGIFT-COST-QUOTE-ENGINE-20260913.md"
  },
  {
    "id": "TASK-ZAI-055",
    "sprint": "SPR-ZAI-03",
    "title": "PricingRuleSet — versioned, owner-approved pricing rules ported from pricing_rules_formula.yaml with per-block provenance, and the Pricing Rules console",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-052",
    "authority": "ROADMAP.md",
    "evidence": "PR #448 merged at c20641f; hosted govern/tests/build/verify passed; E2E/Desktop skipped; production and owner activation NOT_RUN; ../domains/commerce/features/FR-253-pricing-rules-and-engine.md"
  },
  {
    "id": "TASK-ZAI-056",
    "sprint": "SPR-ZAI-03",
    "title": "One pure pricing engine in integer satang — landed cost, ladder, profit floor and ten-baht round-up — with parity fixtures against price-boss; the FR-181 quote tool reads the rule set",
    "status": "review",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-054; TASK-ZAI-055",
    "authority": "ROADMAP.md",
    "evidence": "PR #487 merged at 5b2964c5; hosted Governance changes/govern/tests/build/verify and Edge changes/edge-verify passed; Governance E2E and Edge Desktop skipped; price-boss parity vectors are captured fixtures, not live cross-repository proof; DOD acceptance/success/exit criteria remain unchecked; production, owner approval/activation, deployment, migrations, MSP and GKS NOT_RUN; ../domains/commerce/features/FR-253-pricing-rules-and-engine.md"
  },
  {
    "id": "TASK-ZAI-057",
    "sprint": "SPR-ZAI-03",
    "title": "Quotations — Quote and QuoteLine with ladder snapshots, two-hat approval, the QUOTATION document and conversion to a sales order with the FR-180 hold",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-056; TASK-ZAI-039",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../change-requests/ZAI-PROPOSAL-SMARTGIFT-COST-QUOTE-ENGINE-20260913.md"
  },
  {
    "id": "TASK-ZAI-058",
    "sprint": "SPR-ZAI-04",
    "title": "Ladder quotation on LINE (FR-132) over the shared engine with a deterministic intent matcher",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-057; TASK-ZAI-036",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../change-requests/ZAI-PROPOSAL-SMARTGIFT-COST-QUOTE-ENGINE-20260913.md"
  },
  {
    "id": "TASK-ZAI-059",
    "sprint": "SPR-ZAI-04",
    "title": "Knowledge structured records — STRUCTURED_RECORDS_V1 JSON format, an Excel template and converter, and MCP format widening before Stage 1",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-045; TASK-ZAI-042",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../change-requests/ZAI-PROPOSAL-SMARTGIFT-COST-QUOTE-ENGINE-20260913.md"
  },
  {
    "id": "TASK-ZAI-060",
    "sprint": "SPR-ZAI-02",
    "title": "Data pipeline map decision record — the ADR for a Knowledge (GKS) navigation slot that consumes GKS without becoming it, and the requirement and FEAT declarations",
    "status": "done",
    "proofScope": "SPEC",
    "implementationState": "UNKNOWN",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-061",
    "sprint": "SPR-ZAI-02",
    "title": "Data pipeline registry — the written map of inbound sources, outbound recipients and combine chains, a validated JSON registry, a generated runtime projection and a preflight check",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-060",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-062",
    "sprint": "SPR-ZAI-02",
    "title": "Data Pipeline Map node-edge view under the Knowledge (GKS) slot — layered graph, chain, domain and status filters, edge detail with domain, FEAT and surface level, and a list view",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-061",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-063",
    "sprint": "SPR-ZAI-03",
    "title": "Live pipeline health on the map — per-edge run and job counts for the active Business from the FR-071 ledger and the transport job tables",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-062; TASK-ZAI-047",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-064",
    "sprint": "SPR-ZAI-02",
    "title": "Delivery telemetry decision record — the ADR that lets the programme board show measured time and tokens beside the plan without turning either into completion, the sizing table, and the requirement and FEAT declarations",
    "status": "done",
    "proofScope": "SPEC",
    "implementationState": "UNKNOWN",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-065",
    "sprint": "SPR-ZAI-02",
    "title": "Phase card delivery metrics — sprint and task counts, size in complexity points, plan window and effort estimate, actual time and measured tokens once done, and done or review cards tinted green or orange",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-064",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-066",
    "sprint": "SPR-ZAI-02",
    "title": "Usage meter — measured tokens and active time per task from Claude Code and Codex session logs, attributed by the branches each Task Container declares and written back with provenance",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-064",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-067",
    "sprint": "SPR-ZAI-02",
    "title": "Usage report endpoint — an operator-authenticated ledger where agents without local logs report per-session tokens for a task, idempotent by session and merged with metered sessions without double counting",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-066",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-068",
    "sprint": "SPR-ZAI-02",
    "title": "Task card evidence badges and subtask progress — DOC, CODE, TEST, FR, NFR and FEAT badges coloured green for done, orange for review, red for needs fix and gray for empty, domain, complexity and priority badges, and P0 to P3 subtasks with a progress bar on the card",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-064",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-069",
    "sprint": "SPR-ZAI-02",
    "title": "Harness usage plugin decision record — the ADR for a Zuri plugin that pairs a device by browser approval, holds a report-only credential with a device label, and lets the server attribute each report to a person, a device and a lane; requirement and FEAT declarations",
    "status": "done",
    "proofScope": "SPEC",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-067",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-070",
    "sprint": "SPR-ZAI-02",
    "title": "Harness device pairing and report-only credential — start, browser approval with a check code and poll as in FR-144, one hashed credential per installation scoped to usage reporting with a device label, and an operator list of paired devices with revoke",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-069",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-071",
    "sprint": "SPR-ZAI-02",
    "title": "Usage reports attributed to person, device and lane — the report endpoint accepts the harness credential, derives the lane from the reported branch on the server, extends a resumed session whose counts only grow, and the board breaks lane usage down by person and shows unattributed reports",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-070",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-072",
    "sprint": "SPR-ZAI-02",
    "title": "Zuri harness plugin for Claude Code and Codex — pair, whoami and unpair commands, a SessionEnd hook and a Codex wrapper that report each finished session split by branch, an offline retry queue, a marketplace entry, and parser parity with the usage meter",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-070; TASK-ZAI-071",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-073",
    "sprint": "SPR-ZAI-02",
    "title": "Zuri harness plugin specification — one document for the CLI, hook input, configuration and queue formats, pairing state machine, counting rules, keep-or-drop rules per response, Codex wrapper, log-format compatibility, versioning and privacy, each rule linked to the test that proves it",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-072",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-074",
    "sprint": "SPR-ZAI-02",
    "title": "Agent usage detail capture — thinking and reasoning tokens, cache writes by lifetime, tool calls by name with errors and denials, web search and fetch, user prompts, compactions and errors, measured by the meter and the plugin with parity, carried by the report endpoint and stored for each lane, person and device",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-072",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-075",
    "sprint": "SPR-ZAI-02",
    "title": "Usage detail on the programme board — phase and task telemetry show input, output, thinking and cache tokens separately, tool calls with the most used tools and the error rate, prompts and compactions, per lane, person and device",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-074",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-076",
    "sprint": "SPR-ZAI-02",
    "title": "LINE OA platform decision record — ADR-089 credential vault and self-serve onboarding, ADR-090 GKS grounding and reviewed candidates, ADR-091 chat record, memory tiers and the Context Composer, with FR-223 to FR-238, SEC-030 to SEC-032, SDD-097 to SDD-100 and FEAT-036 to FEAT-038 declared",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "—",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-077",
    "sprint": "SPR-ZAI-02",
    "title": "LINE OA platform delivery plan — every phase of ADR-089 to ADR-091 registered as sized tasks with acceptance criteria, lanes bound to branches before work starts, the usage-detail capture of TASK-ZAI-074 and TASK-ZAI-075 named as the measurement prerequisite, the Project Manager import path stated, and the usage meter run",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-076",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-078",
    "sprint": "SPR-ZAI-03",
    "title": "Integration credential vault — a SecretStorePort with the Supabase Vault and envelope stores, a dispatching secret manager by reference prefix, versioned write, activate, rotate, revoke and resolve with compensation and re-entry status, and design migrations 1, 3 and 4 — FR-223, SEC-030, SDD-097",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-077; TASK-ZAI-074; TASK-ZAI-075",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-079",
    "sprint": "SPR-ZAI-03",
    "title": "LINE channel account claim and the Integration LINE channel-admin port — an installation-wide claim by destination hash taken before any secret is stored, stateless token minting with a per-version cache, bot info, and webhook set, read and test calls, with design migration 2 — FR-226, SDD-098 and the port half of FR-227",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-078",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-080",
    "sprint": "SPR-ZAI-03",
    "title": "Credential-write step-up gate and the first rate limit — assertSessionAssurance AAL2 on every credential write, rotation, revocation and validation, an enrolment redirect when no factor exists, and a RateLimitBucket store answering 429 with retry hints, design migration 8 — FR-224",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-078",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-081",
    "sprint": "SPR-ZAI-03",
    "title": "Phase 1 acceptance — ADR-089 proofs 1 to 6 on SQLite and Postgres with both stores, and one real LINE test channel validated end to end through the connection route in a dev deployment, before any production migration",
    "status": "blocked",
    "proofScope": "UNKNOWN",
    "implementationState": "BLOCKED",
    "dependsOn": "TASK-ZAI-079; TASK-ZAI-080",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-082",
    "sprint": "SPR-ZAI-04",
    "title": "Self-serve LINE OA connection wizard — Thai step-up, Channel ID and secret entry with an optional override token, live proof with LINE, claim, vault write, connection, a masked credential card and a DRAFT account, and a mount-backed account moved into the vault on re-entry — FR-225",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-081",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-083",
    "sprint": "SPR-ZAI-04",
    "title": "Automatic LINE webhook registration and health — a publisher action sets, reads back and tests the account webhook through LINE, stores webhook health in LineOaAccount.webhookStateJson with its migration, and falls back to a Thai manual card — FR-227",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-082",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-084",
    "sprint": "SPR-ZAI-04",
    "title": "Derived legacy-transport quiescence and restore re-entry — ENABLE_SERVER derives quiescence for a vault-backed account from the endpoint LINE reports and 120 seconds without legacy evidence, validates through the dispatching secret manager, and a restored snapshot forces credential re-entry — FR-228",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-083",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-085",
    "sprint": "SPR-ZAI-04",
    "title": "Apply the credential vault and onboarding migrations on production — design migrations 1 to 4 and 8 and the webhook-state column, under ADR-057 with an inventory, a rolled-back dry run and a verified effect, recorded in the migration notes",
    "status": "in-progress",
    "proofScope": "UNKNOWN",
    "implementationState": "IN_PROGRESS",
    "dependsOn": "TASK-ZAI-084",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-086",
    "sprint": "SPR-ZAI-04",
    "title": "Channel credential entry for the first production account — the Business owner, at AAL2, enters the Channel ID and secret in the production wizard to move one mount-backed LINE OA account into the vault; no agent ever types a credential",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-085",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-087",
    "sprint": "SPR-ZAI-04",
    "title": "Webhook cutover for the first production account — register and test the webhook through LINE, observe derived quiescence, enable server transport and record ADR-061 provider-webhook-replaced evidence with a written rollback",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-086",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-088",
    "sprint": "SPR-ZAI-04",
    "title": "Non-text LINE content in the CRM record — sticker, location and media messages become Message rows with a content kind and placeholder body, media gets a MessageAttachment without bytes, follow, join, membership, postback and unsend become ConversationEvent rows, and an unsend tombstones its message — FR-229",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-077; TASK-ZAI-074; TASK-ZAI-075",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-089",
    "sprint": "SPR-ZAI-04",
    "title": "Declared retention classes and the nightly sweep — installation defaults for raw LINE payloads, message bodies and attachments, trace payloads and MSP session content, per-Tenant downward-only overrides, a sweep that skips rows live LINE jobs reference, and one audit event per run — FR-230, SEC-031",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-088",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-090",
    "sprint": "SPR-ZAI-04",
    "title": "Conversation inbox read models and message search — last-message time, a redacted 120-character preview, retention class and unread counts, a read-only CRM search reader with a trigram index on Postgres, and follow and unfollow counts per account — FR-233",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-088",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-091",
    "sprint": "SPR-ZAI-04",
    "title": "Apply the chat record migrations on production — non-text content, read-model columns, the trigram index and the retention override store, under ADR-057, recorded in the migration notes",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-089; TASK-ZAI-090",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-092",
    "sprint": "SPR-ZAI-05",
    "title": "Context Composer — one agent-lane module assembling every LINE model prompt from AuthContext, MSP slices, knowledge evidence and CRM and ERP facts in truth order under one budget, reporting every trim, recording one ContextReceipt per model invocation and calling no model without evidence — FR-234, SDD-100",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-088",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-093",
    "sprint": "SPR-ZAI-05",
    "title": "LINE grounding from the published corpus — an in-process knowledge.query reader over queryKnowledgeCorpus under the runtime knowledge capability, a per-account knowledgeGrounding mode with its migration, a 2 500 ms, top-5, 8 KiB budget, a traced mode-gated fallback and retrievalRefs on EVIDENCE_SELECTED — FR-235, SDD-099",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-092",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-094",
    "sprint": "SPR-ZAI-05",
    "title": "Grounding isolated acceptance — a real LINE job answered from a published generation in the four-process harness with citations on the job trace, zero cross-tenant leakage, the deterministic reply with the worker stopped, and MSP spawn cost measured against the budget",
    "status": "done",
    "proofScope": "LOCAL",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-093",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-095",
    "sprint": "SPR-ZAI-06",
    "title": "SmartGift grounding switch on production — after ADR-075 Phase 3 is deployed, apply the grounding-mode migration, switch one SmartGift DIRECT account to GKS_THEN_BUSINESS_KNOWLEDGE as an owner-triggered operator step, shadow-compare for one campaign window and keep the rollback",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-094; TASK-ZAI-042; TASK-ZAI-050",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-096",
    "sprint": "SPR-ZAI-06",
    "title": "LINE FAQ knowledge candidates — locator-only question-and-answer candidates from consent-GRANTED conversations checked by the Zero-PII deny policy, an OWNER or LINE_OA_PUBLISHER review surface with audited decisions, and admission of an approved candidate as a LINE_FAQ_CANDIDATE TEXT source through ADR-072 — FR-236, SEC-032",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-093",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-097",
    "sprint": "SPR-ZAI-06",
    "title": "Knowledge gap report for LINE — NO_EVIDENCE retrievals aggregated per Business in the Knowledge (GKS) slot as counts, product locators and last-seen times, with the question text left in CRM — FR-237",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-093",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-098",
    "sprint": "SPR-ZAI-06",
    "title": "LINE Studio descriptions as knowledge sources — on a publisher action, published rich menu, LIFF app and bot profile descriptions are admitted as LINE_STUDIO_DESCRIPTION TEXT sources, never the Flex or rich menu JSON, and unpublishing withdraws them — FR-238",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-096",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-099",
    "sprint": "SPR-ZAI-06",
    "title": "Apply the knowledge candidate migration on production and turn candidates on for SmartGift only on the owner's instruction, recorded in the migration notes",
    "status": "in-progress",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-096",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-100",
    "sprint": "SPR-ZAI-06",
    "title": "LINE memory projection policy and receipts — LineOaAccount.memoryPolicy defaulting to OFF, per-job capture of session-tier and memory-tier eligibility by policy, consent and audience, MemoryProjectionReceipt in the delivery settlement, and a projector that refuses until MSP main ships thread and erase tools — FR-231",
    "status": "blocked",
    "proofScope": "HOSTED_CI",
    "implementationState": "BLOCKED",
    "dependsOn": "TASK-ZAI-092; TASK-ZAI-089",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-101",
    "sprint": "SPR-ZAI-06",
    "title": "Erasure propagation beyond Tier 1 — one transaction tombstones CRM bodies, previews, attachments, LINE job fields, raw payloads, trace inputs and knowledge candidates, and leaves durable MSP erase calls per projection receipt and knowledge-source withdrawals, with PENDING_MSP until acknowledged — FR-232, SEC-031",
    "status": "blocked",
    "proofScope": "UNKNOWN",
    "implementationState": "BLOCKED",
    "dependsOn": "TASK-ZAI-100; TASK-ZAI-096",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-102",
    "sprint": "SPR-ZAI-06",
    "title": "Memory policy production activation — apply the memory policy and projection receipt migrations under ADR-057 and, only on the owner's instruction, enable projection for one DIRECT account after the MSP canary (TASK-MEMOS-006) passes, recorded with a rollback",
    "status": "blocked",
    "proofScope": "UNKNOWN",
    "implementationState": "BLOCKED",
    "dependsOn": "TASK-ZAI-101",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-103",
    "sprint": "SPR-ZAI-10",
    "title": "Generalise the credential vault to other provider kinds, FR-242 — OAUTH_CLIENT for FlowAccount (ADR-053) and MODEL_PROVIDER_KEY on the same SecretStorePort, built and tested; retiring the Phase-1 model-credential resolver is a separate follow-up",
    "status": "review",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-085",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-104",
    "sprint": "SPR-ZAI-02",
    "title": "Programme roadmap member view — for 30 days any signed-in person reads the programme plan and the Domain map at /roadmap, with usage by person and device, tool and model names and the Agent devices tab removed on the server, closing by itself at 2026-10-15 00:00 Asia/Bangkok while /control/roadmap stays operator-only",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-075",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-105",
    "sprint": "SPR-ZAI-02",
    "title": "Conversation sessions and chat evidence decision records — ADR-093 and ADR-094 accepted with the owner's choices, FR-243 to FR-246, SEC-034, SDD-102, SDD-103, FEAT-040 and FEAT-041 declared, SEC-031 re-worded, and tasks 105 to 115 bound to lanes",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-091",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-106",
    "sprint": "SPR-ZAI-03",
    "title": "Conversation sessions, FR-243 — ConversationSession model and migration, session assignment inside LINE admission and reply recording, the per-account idle timeout column, and a backfill of existing messages by the same rule",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-105",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-107",
    "sprint": "SPR-ZAI-03",
    "title": "Sessions on the LINE job, trace and inbox, FR-243 — the session id on LineConversationJob, a trace filter by session, a divider between sessions in the inbox, and the account setting for the idle timeout",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-106",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-108",
    "sprint": "SPR-ZAI-03",
    "title": "Apply the conversation session migration on production and run the backfill, under ADR-057 with an inventory, a rolled-back dry run and a verified effect, recorded in the migration notes",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "TASK-ZAI-107",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-109",
    "sprint": "SPR-ZAI-04",
    "title": "Local model residency by business hours, FR-244 — per-account business hours and out-of-hours reply, the edge worker loading the model during any served account's hours and unloading it after the last closes, and no model call outside hours",
    "status": "review",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-105",
    "authority": "ROADMAP.md",
    "evidence": "PR #427 implementation merged at `09fc5978`; PR #476 fix merged at `95edda4c`; hosted Governance #1197/#1327 and Edge #531/#657 passed with E2E skipped; migration `20260916130000_line_oa_business_hours.sql`, matching Server+Edge deployment, release after last account closes, out-of-hours no-model reply receipt, no-declared-hours behavior, first reply after 09:00 ICT and immutable production receipt remain open; production/owner activation NOT_RUN"
  },
  {
    "id": "TASK-ZAI-110",
    "sprint": "SPR-ZAI-04",
    "title": "Staff replies recorded, FR-246 — a member with CRM write access replies from the inbox, the server pushes it through the account's LINE transport and records an OUTBOUND message with reply source STAFF in the conversation's session",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "DEPLOYED",
    "dependsOn": "TASK-ZAI-106",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-111",
    "sprint": "SPR-ZAI-05",
    "title": "Chat evidence archive writer, FR-245 — archive manifest model and migration, per-Customer AES-256-GCM segments under ZURI_ARCHIVE_KEK, write-flush-verify before tombstone inside the retention sweep, failing closed",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-108; TASK-ZAI-110",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-112",
    "sprint": "SPR-ZAI-05",
    "title": "Chat evidence retrieval, FR-245 — an OWNER at AAL2 retrieves one Customer's archived messages for a date range by session with a case reference, as an export carrying file and manifest hashes, audited",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-111",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-113",
    "sprint": "SPR-ZAI-05",
    "title": "Archive key destruction and the legal hold, SEC-034 — expiry and PDPA erasure destroy a Customer's archive data key unless an OWNER-recorded legal hold with a reason and end date is active, shown on the erasure status",
    "status": "review",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-112",
    "authority": "ROADMAP.md",
    "evidence": "PR #451 head `8180bef2` merged as `cfd5521e`; implementation commit `badc11ee` is an ancestor on current main; hosted Governance #1261, Edge #594 and Docker #288 passed; archive legal-hold/key-destruction migration(s) written but not applied to production; production archive mount/KEK and live expiry/erasure/legal-hold behavior unproven; owner/legal receipt and deployment/rollback evidence remain NOT_RUN; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-114",
    "sprint": "SPR-ZAI-06",
    "title": "Chat evidence archive on production — the cold-archive compose overlay on F:, ZURI_ARCHIVE_KEK with its offline backup, the migrations applied under ADR-057, the sweep token and 03:00 scheduled task, and the first recorded manifest",
    "status": "review",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-113",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-115",
    "sprint": "SPR-ZAI-06",
    "title": "Monthly offline copy of the chat evidence archive — new archive files copied to an offline external drive and verified against the manifest hashes, with the first verified copy recorded",
    "status": "planned",
    "proofScope": "UNKNOWN",
    "implementationState": "NOT_STARTED",
    "dependsOn": "TASK-ZAI-114",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-116",
    "sprint": "SPR-ZAI-02",
    "title": "Observability decision record — ADR-095 for error tracking and per-person feature usage, and the FR/NFR declarations it governs",
    "status": "done",
    "proofScope": "UNKNOWN",
    "implementationState": "UNKNOWN",
    "dependsOn": "",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-117",
    "sprint": "SPR-ZAI-02",
    "title": "Error tracking — logger.exception() fingerprints and dedupes errors into a durable, operator-readable ErrorEvent table with a resolve action",
    "status": "done",
    "proofScope": "PRODUCTION",
    "implementationState": "ACTIVE",
    "dependsOn": "TASK-ZAI-116",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-118",
    "sprint": "SPR-ZAI-02",
    "title": "Feature usage — UsageEvent at route and action level, per person, with a 90-day raw window then an aggregate-only rollup",
    "status": "done",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-116",
    "authority": "ROADMAP.md",
    "evidence": "ROADMAP task row; ../roadmap/ROADMAP-zuri-ai-24w-program.md"
  },
  {
    "id": "TASK-ZAI-119",
    "sprint": "SPR-ZAI-02",
    "title": "Mission Control DAG orchestration observability — FEAT-044 and FR-260..264, read-only operator projection with candidate-parallel merge gates and provenance-bound PORL observations",
    "status": "review",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-064",
    "authority": "ROADMAP.md",
    "evidence": "PR #468; approved head 53a2439ad722ca32797db381f3e3f46360ffd5d8; merge commit 0932f31e2e130af95b0a889772005281ffc8d112; hosted tests/govern/build/edge-verify/changes passed; desktop/e2e remained skipped by repository policy; targeted local receipt `.brain/reports/task-zai-119-responsive-receipt.json` records 1/1 passed at 390x844 and 430x932 with retry 0/flaky 0; PORL unavailable; no deployment or production activation claimed; production/PORL observation NOT_RUN"
  },
  {
    "id": "TASK-ZAI-120",
    "sprint": "SPR-ZAI-10",
    "title": "LINE OA on API keys only (FEAT-045; FR-265, FR-266) — retire EDGE execution from the Studio and provision the Business-scoped model provider key in the browser through the existing credential vault; server execution is CLOUD/SERVER only and resolution fails closed on a broken present credential",
    "status": "review",
    "proofScope": "HOSTED_CI",
    "implementationState": "MERGED",
    "dependsOn": "TASK-ZAI-103",
    "authority": "ROADMAP.md",
    "evidence": "PR #500 merged at `cfb62da3` from `d227ac23`; Governance #1393 and Edge #722 passed required checks with E2E/Desktop skipped; migration `20260921090000` is not applied; deployment, owner provider canary and production remain NOT_RUN; Phase-1 resolver retirement is a separate TASK-ZAI-103 exit gate"
  }
]

export const ROADMAP_TASK_STATUS = Object.freeze(Object.fromEntries(ROADMAP_TASK_LEDGER.map((row) => [row.id, row.status])))
