'use client'

// @req FR-252 — typed policy controls, safe formula authoring and server-result comparison.
// @spec ADR-097
// @tested tests/unit/pricing-rules-ui.test.js, tests/e2e/fr252-pricing-rules.spec.js

export const fieldClass = 'w-full rounded-lg border border-[var(--border)] bg-white p-2 text-sm disabled:bg-[var(--surface-mid)]'
export const money = (satang) => satang == null ? '—' : `${new Intl.NumberFormat('th-TH', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(satang) / 100)} บาท`
const clone = (value) => JSON.parse(JSON.stringify(value))
export function setAtPath(value, path, next) {
  const copy = clone(value)
  let target = copy
  for (const key of path.slice(0, -1)) target = target[key]
  target[path.at(-1)] = next
  return copy
}
export function Field({ label, hint, ...props }) {
  return <label className="grid content-start gap-1 text-xs font-semibold">{label}<input className={fieldClass} aria-label={label} {...props} />{hint && <span className="font-normal text-muted">{hint}</span>}</label>
}
export function SelectField({ label, options, ...props }) {
  return <label className="grid content-start gap-1 text-xs font-semibold">{label}<select className={fieldClass} aria-label={label} {...props}>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>
}

const LABELS = {
  targetProfitThb: 'เป้ากำไรทั้งงาน (เตือนเท่านั้น; ว่าง = ไม่กำหนด)', marginWarningBand: 'ช่วงกำไรสำหรับแจ้งเตือน', minPercent: 'เปอร์เซ็นต์ต่ำสุด', maxPercent: 'เปอร์เซ็นต์สูงสุด', cnyToThb: 'CNY → THB', usdToThb: 'USD → THB', densityThreshold: 'เกณฑ์ความหนาแน่น', minCbm: 'ปริมาตรขั้นต่ำ', seaThresholdCbm: 'เกณฑ์ขนส่งทางเรือ', peakMonths: 'เดือนช่วงสูงสุด', forceTruckInPeak: 'ใช้รถในช่วงสูงสุด', inlandCnyPerUnit: 'ขนส่งในจีนต่อชิ้น', domesticSingleDropThb: 'ส่งในประเทศหนึ่งจุด', rates: 'อัตราขนส่ง', guangzhou_shenzhen: 'กวางโจว / เซินเจิ้น', yiwu: 'อี้อู', truck: 'รถ', sea: 'เรือ', general: 'สินค้าทั่วไป', electronic_tisi: 'อิเล็กทรอนิกส์ / มอก.', cbm: 'อัตราต่อปริมาตร', kg: 'อัตราต่อน้ำหนัก', priceStepThb: 'ขั้นปัดราคาขาย', maxQty: 'จำนวนสูงสุด (ว่าง = ไม่จำกัด)', minQty: 'จำนวนเริ่มต้น', thb: 'จำนวนเงิน', factor: 'ตัวคูณ', maxCostThb: 'ต้นทุนสูงสุด (ว่าง = ไม่จำกัด)', multiplier: 'ตัวคูณราคา', standard: 'ทั่วไป', corporate: 'องค์กร', name: 'ชื่อ', basis: 'ฐานต้นทุน', anchorQty: 'จำนวนอ้างอิง', breaks: 'จำนวนแต่ละระดับ', factors: 'ตัวคูณแต่ละระดับ', flatMarkup: 'Markup คงที่ (ว่าง = ใช้ตาราง)', referenceGoodsType: 'ประเภทสินค้าอ้างอิง', set: 'สินค้าชุด', single: 'สินค้าชิ้น', flatThbPerPosition: 'สกรีนอัตราคงที่ต่อตำแหน่ง', hotstampSetupUsd: 'ค่าเตรียมปั๊ม', hotstampBaseQty: 'จำนวนฐานปั๊ม', hotstampTiers: 'อัตราปั๊มตามจำนวน', hotstampTextUsd: 'ค่าปั๊มข้อความ', engraveTiers: 'อัตราเลเซอร์ตามจำนวน', usd: 'อัตรา USD', silkFlatUpToQty: 'จำนวนสูงสุดอัตราเหมาซิลค์', silkFlatUsd: 'ราคาเหมาซิลค์', silkPerPieceUsd: 'ซิลค์ต่อชิ้น', uvPerPieceUsd: 'UV ต่อชิ้น (ว่าง = ต้องระบุเฉพาะงาน)', piecesFromCodeLastDigit: 'อ่านจำนวนชิ้นจากท้ายรหัสสินค้า', extraPositions: 'ตำแหน่งเพิ่มเติม', minPositions: 'ตำแหน่งขั้นต่ำ', artwork: 'ออกแบบ', sample: 'ตัวอย่าง', production: 'ผลิต', freight: 'ขนส่ง', min: 'ต่ำสุด', max: 'สูงสุด', ELITE: 'ELITE', GOLD: 'GOLD', SILVER: 'SILVER', MEMBER: 'MEMBER',
}
function unitFor(path) {
  const key = path.at(-1), joined = path.join('.')
  if (String(key).endsWith('Percent')) return '%'
  if (key === 'cnyToThb') return 'THB/CNY'
  if (key === 'usdToThb') return 'THB/USD'
  if (key === 'densityThreshold') return 'kg/m³'
  if (key === 'cbm') return 'THB/m³'
  if (key === 'kg') return 'THB/kg'
  if (/Cbm$/.test(key)) return 'm³'
  if (key === 'inlandCnyPerUnit') return 'CNY/ชิ้น'
  if (/Usd$/.test(key) || key === 'usd') return 'USD'
  if (/Thb$/.test(key) || key === 'thb') return 'THB'
  if (/Qty$/.test(key) || joined.includes('.breaks.')) return 'ชิ้น'
  if (joined.startsWith('leadTime.') && ['min', 'max'].includes(key)) return 'วัน'
  if (joined.includes('peakMonths')) return 'เดือน 1–12'
  if (/Positions$/.test(key)) return 'ตำแหน่ง'
  if (/factor|markup|multiplier/i.test(joined)) return 'อัตราส่วน'
  return ''
}

function PolicyNode({ value, path, onChange }) {
  const key = path.at(-1), label = LABELS[key] || (Number.isInteger(key) ? `รายการ ${key + 1}` : key)
  if (Array.isArray(value)) return <fieldset className="space-y-3 rounded-lg border border-[var(--border)] p-3"><legend className="px-1 text-sm font-semibold">{label}</legend>{value.map((item, i) => <div key={i} className="flex items-start gap-2"><div className="min-w-0 flex-1"><PolicyNode value={item} path={[...path, i]} onChange={onChange} /></div><button type="button" className="btn text-xs" aria-label={`ลบ ${path.join('.')} รายการ ${i + 1}`} disabled={value.length === 1} onClick={() => onChange(path, value.filter((_, j) => i !== j))}>ลบ</button></div>)}<button type="button" className="btn text-xs" disabled={!value.length} onClick={() => onChange(path, [...value, clone(value.at(-1))])}>เพิ่ม {label}</button><p className="text-xs text-muted">ลำดับและช่วงจำนวนต้องผ่านการตรวจของระบบก่อนบันทึก</p></fieldset>
  if (value && typeof value === 'object') return <fieldset className="grid gap-3 rounded-lg border border-[var(--border)] p-3 md:grid-cols-2"><legend className="px-1 text-sm font-semibold">{label}</legend>{Object.entries(value).map(([child, item]) => <div key={child} className={item && typeof item === 'object' ? 'md:col-span-2' : ''}><PolicyNode value={item} path={[...path, child]} onChange={onChange} /></div>)}</fieldset>
  const aria = `${path.map((p) => LABELS[p] || p).join(' / ')}${unitFor(path) ? ` (${unitFor(path)})` : ''}`
  if (typeof value === 'boolean') return <label className="flex items-center gap-2 text-sm"><input aria-label={aria} type="checkbox" checked={value} onChange={(e) => onChange(path, e.target.checked)} />{label}</label>
  if (key === 'basis' || key === 'referenceGoodsType') return <SelectField label={aria} value={value ?? ''} options={key === 'basis' ? [['factory', 'ต้นทุนโรงงาน'], ['landed', 'ต้นทุนถึงไทย']] : [['', 'ไม่กำหนด'], ['general', 'ทั่วไป'], ['electronic_tisi', 'อิเล็กทรอนิกส์ / มอก.']]} onChange={(e) => onChange(path, e.target.value || null)} />
  const text = key === 'name'
  return <Field label={aria} type={text ? 'text' : 'number'} step="any" value={value ?? ''} onChange={(e) => onChange(path, e.target.value === '' ? null : typeof value === 'number' || String(key).endsWith('Qty') || ['extraPositions', 'minPositions'].includes(key) || key === 'min' || key === 'max' || path.includes('breaks') || path.includes('peakMonths') ? Number(e.target.value) : e.target.value)} />
}

const GROUPS = [['fx', 'อัตราแลกเปลี่ยน'], ['logistics', 'ขนส่งเข้าและส่งในประเทศ'], ['logo', 'งานปรับแต่งและสกรีน'], ['logoPositions', 'จำนวนตำแหน่งสกรีน'], ['profiles', 'Ladder และกลุ่มลูกค้า'], ['markupBands', 'Markup ตามต้นทุน'], ['quantityFloors', 'กำไรขั้นต่ำตามจำนวน'], ['kindFloors', 'กำไรขั้นต่ำตามชนิดสินค้า'], ['smallOrderFactors', 'ตัวคูณงานจำนวนน้อย'], ['rounding', 'การปัดราคาขาย'], ['leadTime', 'ระยะเวลาผลิตและส่ง']]
export function PricingVariables({ rules, onChange, disabled }) {
  return <fieldset disabled={disabled} className="space-y-3"><p className="text-sm text-muted">ตัวแปรนโยบายธุรกิจ · ค่าต้นทางรุ่น {rules.version} · ค่าที่ทดลองเฉพาะงานอยู่ในแท็บทดลองคำนวณ</p>{GROUPS.filter(([key]) => rules[key] != null).map(([key, label]) => <details key={key} className="rounded-xl border border-[var(--border)] bg-white p-3"><summary className="cursor-pointer font-semibold">{label}</summary><div className="mt-3"><PolicyNode value={rules[key]} path={[key]} onChange={(path, next) => onChange(setAtPath(rules, path, next))} /></div></details>)}<details className="rounded-lg border border-[var(--border)] p-3"><summary className="cursor-pointer text-sm font-semibold">ที่มาของนโยบายและส่วนที่ยังไม่เปิดใช้</summary><p className="mt-2 text-xs">{rules.provenance.sourcePath} · รุ่น {rules.provenance.sourceVersion} · วันที่ต้นทาง {rules.provenance.sourceContext?.updatedAt || '—'}</p><p className="break-all text-xs text-muted">SHA-256: {rules.provenance.sourceSha256}</p><ul className="mt-2 list-inside list-disc text-xs">{rules.provenance.importNotes?.map((note, i) => <li key={i}>{note}</li>)}</ul><p className="mt-2 text-xs">SRP benchmark และขนส่งในจีนแบบ CBM: ยังไม่เปิดใช้ในเครื่องคำนวณนี้ จึงไม่มีช่องแก้ไข</p></details><p className="text-xs text-muted">VAT ของเอกสารใช้การตั้งค่าเอกสารขาย ไม่ใช่สูตรราคานี้</p></fieldset>
}

const VARIABLES = { quantity: 'ชิ้น', landedCost: 'THB/ชิ้น', factoryCost: 'THB/ชิ้น', anchorPrice: 'THB/ชิ้น', factor: 'อัตราส่วน', anchorFactor: 'อัตราส่วน', markup: 'อัตราส่วน', orderCost: 'THB', profitFloor: 'THB', priceStep: 'THB/ชิ้น' }
export function PricingFormulas({ rules, onChange, disabled, errors = [] }) {
  const update = (i, key, value) => onChange(setAtPath(rules, ['formulas', i, key], value))
  return <fieldset disabled={disabled} className="space-y-4"><p className="text-sm text-muted">ใช้ + − * / วงเล็บ min, max, ceilToStep และ quantityBand · ผล candidatePrice เป็น THB/ชิ้น ระบบบังคับกำไรขั้นต่ำและปัดราคาหลังสูตรเสมอ</p>{rules.formulas.map((formula, i) => <div key={i} className="space-y-3 rounded-xl border border-[var(--border)] p-4"><div className="grid gap-3 md:grid-cols-2"><Field label={`ชื่อขั้นคำนวณ ${i + 1}`} value={formula.name} onChange={(e) => update(i, 'name', e.target.value)} /><SelectField label={`หน่วยผลลัพธ์ ${i + 1}`} value={formula.unit} options={['THB/unit', 'THB', 'ratio', 'unit'].map((v) => [v, v])} onChange={(e) => update(i, 'unit', e.target.value)} /></div><label className="grid gap-1 text-sm font-semibold">นิพจน์ {formula.name}<textarea className={`${fieldClass} min-h-24 font-mono`} aria-label={`นิพจน์ ${formula.name}`} value={formula.expression} onChange={(e) => update(i, 'expression', e.target.value)} /></label><div className="flex flex-wrap gap-2">{['min(', 'max(', 'ceilToStep(', 'quantityBand(', ...Object.keys(VARIABLES)].map((v) => <button key={v} type="button" className="btn px-2 py-1 text-xs" aria-label={`แทรก ${v} ในขั้น ${i + 1}`} onClick={() => update(i, 'expression', `${formula.expression} ${v}`)}>{v}</button>)}</div>{errors.filter((e) => e.field?.includes('formula')).map((e, index) => <p role="alert" className="text-sm text-red-700" key={index}>{e.field}: {e.message}</p>)}<button type="button" className="btn text-xs" disabled={formula.name === 'candidatePrice'} onClick={() => onChange({ ...rules, formulas: rules.formulas.filter((_, j) => j !== i) })}>ลบขั้นคำนวณ {i + 1}</button></div>)}<button type="button" className="btn" onClick={() => onChange({ ...rules, formulas: [...rules.formulas, { name: `step${rules.formulas.length + 1}`, expression: '', unit: 'THB/unit' }] })}>เพิ่มขั้นคำนวณ</button><details><summary className="cursor-pointer text-sm font-semibold">ตัวแปรที่อ้างอิงและหน่วย</summary><dl className="mt-2 grid grid-cols-2 gap-2 text-sm">{Object.entries(VARIABLES).map(([name, unit]) => <div key={name}><dt className="font-mono">{name}</dt><dd>{unit}</dd></div>)}</dl></details></fieldset>
}

export const emptyPreviewInput = () => ({ costBasis: 'factory', productCode: '', quantity: 100, kind: 'set', profile: 'standard', factoryUnitCost: { amount: '', currency: 'CNY' }, carton: { units: '', cbm: '', kg: null }, shipping: { warehouse: 'guangzhou_shenzhen', mode: 'auto', month: new Date().getMonth() + 1, goodsType: 'general', tier: 'ELITE', domesticMode: 'none' }, logo: { method: 'none', positions: 1, colors: 1 }, extraUnitCostThb: '0', orderCostThb: '0', sourceRefs: [] })
export function PricingPreviewInputs({ input, onChange, disabled }) {
  const field = (path, label, type = 'text', options) => {
    const value = path.reduce((v, key) => v?.[key], input)
    const change = (e) => onChange(setAtPath(input, path, e.target.value === '' ? (['kg', 'positions'].includes(path.at(-1)) ? null : '') : type === 'integer' ? Number(e.target.value) : e.target.value))
    return options ? <SelectField key={label} label={label} value={value ?? ''} onChange={change} options={options} /> : <Field key={label} label={label} type={type === 'integer' || type === 'decimal' ? 'number' : type} step={type === 'integer' ? '1' : 'any'} value={value ?? ''} onChange={change} />
  }
  return <fieldset disabled={disabled} className="grid gap-3 md:grid-cols-3"><p className="text-sm text-muted md:col-span-3">ข้อมูลทดลองที่ผู้ใช้กรอก ยังไม่ใช่ต้นทุนที่ Procurement ยืนยัน การทดลองไม่เปลี่ยนนโยบายหรือเผยแพร่ราคาไป RAG</p>{field(['productCode'], 'รหัสสินค้า (ถ้ามี)')}{field(['quantity'], 'จำนวนทดลอง (ชิ้น)', 'integer')}{field(['kind'], 'ชนิดสินค้า', 'text', [['set', 'ชุด'], ['single', 'ชิ้น']])}{field(['profile'], 'กลุ่มลูกค้าทดลอง', 'text', [['standard', 'ทั่วไป'], ['corporate', 'องค์กร']])}{field(['factoryUnitCost', 'amount'], 'ต้นทุนโรงงานต่อชิ้น', 'decimal')}{field(['factoryUnitCost', 'currency'], 'สกุลเงินต้นทุน', 'text', ['CNY', 'USD', 'THB'].map((v) => [v, v]))}{field(['carton', 'units'], 'จำนวนชิ้นต่อลัง', 'integer')}{field(['carton', 'cbm'], 'ปริมาตรลัง (m³)', 'decimal')}{field(['carton', 'kg'], 'น้ำหนักลัง (kg; ไม่ทราบเว้นว่าง)', 'decimal')}{field(['shipping', 'warehouse'], 'คลังต้นทาง', 'text', [['guangzhou_shenzhen', 'กวางโจว / เซินเจิ้น'], ['yiwu', 'อี้อู']])}{field(['shipping', 'mode'], 'รูปแบบขนส่งเข้า', 'text', [['auto', 'ตามนโยบาย'], ['truck', 'รถ'], ['sea', 'เรือ']])}{field(['shipping', 'month'], 'เดือนขนส่ง (1–12)', 'integer')}{field(['shipping', 'goodsType'], 'ประเภทขนส่ง', 'text', [['general', 'ทั่วไป'], ['electronic_tisi', 'อิเล็กทรอนิกส์ / มอก.']])}{field(['shipping', 'tier'], 'ระดับสมาชิกขนส่ง', 'text', ['ELITE', 'GOLD', 'SILVER', 'MEMBER'].map((v) => [v, v]))}{field(['shipping', 'domesticMode'], 'ส่งในประเทศ', 'text', [['none', 'ไม่รวมส่งในประเทศ'], ['single_drop', 'ส่งหนึ่งจุด']])}{field(['logo', 'method'], 'วิธีสกรีน', 'text', [['none', 'ไม่มี'], ['flat', 'อัตราคงที่'], ['hotstamp', 'ปั๊ม'], ['hotstamp_text', 'ปั๊มข้อความ'], ['engrave', 'เลเซอร์'], ['silk', 'ซิลค์'], ['uv', 'UV']])}{field(['logo', 'positions'], 'ตำแหน่งสกรีน (ว่าง = ตามรหัสสินค้า)', 'integer')}{field(['logo', 'colors'], 'จำนวนสีสกรีน', 'integer')}{input.logo.method === 'uv' && field(['logo', 'uvRateUsd'], 'อัตรา UV เฉพาะงาน (USD/ชิ้น)', 'decimal')}{field(['extraUnitCostThb'], 'ต้นทุนเพิ่มเฉพาะงาน (THB/ชิ้น)', 'decimal')}{field(['orderCostThb'], 'ต้นทุนทั้งงานเพิ่มเติม (THB)', 'decimal')}</fieldset>
}

function flatten(value, prefix = '', result = {}) {
  if (value && typeof value === 'object') for (const [key, entry] of Object.entries(value)) flatten(entry, prefix ? `${prefix}.${key}` : key, result)
  else result[prefix] = value
  return result
}
export function pricingDiff(before, after) {
  const a = flatten(before), b = flatten(after)
  return [...new Set([...Object.keys(a), ...Object.keys(b)])].filter((key) => a[key] !== b[key]).map((key) => ({ key, before: a[key], after: b[key] }))
}
export function PricingDiff({ before, after }) {
  const rows = pricingDiff(before, after)
  return rows.length ? <div className="overflow-x-auto"><table className="w-full text-left text-xs"><caption className="pb-2 text-left text-sm">ความต่างสูตรและตัวแปร ({rows.length} รายการ)</caption><thead><tr><th className="p-2">รายการ</th><th className="p-2">เดิม</th><th className="p-2">ใหม่</th></tr></thead><tbody>{rows.map((row) => <tr key={row.key} className="border-t border-[var(--border)]"><td className="break-all p-2 font-mono">{row.key}</td><td className="p-2">{String(row.before ?? '—')}</td><td className="p-2">{String(row.after ?? '—')}</td></tr>)}</tbody></table></div> : <p className="text-sm text-muted">ไม่มีความต่างของสูตรและตัวแปร</p>
}
const BREAKDOWN_LABELS = { marginPercent: 'อัตรากำไร (%)', targetProfitSatang: 'เป้ากำไรทั้งงาน (เตือนเท่านั้น)', costBasis: 'ฐานต้นทุน', unitLandedCostThbExact: 'ต้นทุนถึงไทยต่อชิ้น (บาท ก่อนปัด)', factoryUnitSatang: 'ต้นทุนโรงงานต่อชิ้น', freightUnitSatang: 'ขนส่งเข้าต่อชิ้น', logoUnitSatang: 'สกรีนต่อชิ้น', inlandUnitSatang: 'ขนส่งในจีนต่อชิ้น', domesticUnitSatang: 'ส่งในประเทศต่อชิ้น', extraUnitSatang: 'ต้นทุนเพิ่มต่อชิ้น', orderCostSatang: 'ต้นทุนทั้งงานเพิ่มเติม', profitFloorSatang: 'กำไรขั้นต่ำทั้งงาน', candidateUnitSatang: 'ราคาจากสูตรก่อนบังคับขั้นต่ำ', smallOrderFactor: 'ตัวคูณงานจำนวนน้อย', appliedMarkup: 'Markup ที่ใช้', 'shipping.cartons': 'จำนวนลัง', 'shipping.volumeCbm': 'ปริมาตรรวม (m³)', 'shipping.weightKg': 'น้ำหนักรวม (kg)', 'shipping.chargedBy': 'ฐานคิดค่าขนส่ง', 'shipping.mode': 'รูปแบบขนส่ง', 'shipping.freightTotalSatang': 'ค่าขนส่งเข้ารวม', 'leadTimeWorkingDays.min': 'ระยะเวลาต่ำสุด (วันทำการ)', 'leadTimeWorkingDays.max': 'ระยะเวลาสูงสุด (วันทำการ)' }
const WARNING_LABELS = { MARGIN_OUTSIDE_PROFILE: 'อัตรากำไรอยู่นอกช่วงแจ้งเตือนของกลุ่มลูกค้า ระบบไม่ได้บังคับเปลี่ยนราคา', BELOW_PROFIT_TARGET: 'กำไรผ่านขั้นต่ำแล้ว แต่ยังต่ำกว่าเป้ากำไรของกลุ่มลูกค้า', MISSING_SOURCE_REFERENCES: 'ยังไม่มีหลักฐานต้นทางของต้นทุน ผลทดลองไม่ได้ยืนยันต้นทุน', MISSING_WEIGHT: 'ไม่ทราบน้ำหนักลัง ระบบคิดขนส่งตามปริมาตร', NO_LOGO: 'ไม่ได้รวมค่าสกรีน โปรดตรวจว่าตรงกับงาน', SMALL_ORDER_FACTOR: 'ใช้ตัวคูณสำหรับงานจำนวนน้อย ต้องตรวจหลักฐานโรงงาน', NO_DOMESTIC_FREIGHT: 'ไม่ได้รวมขนส่งในประเทศ ไม่ใช่การอนุมัติส่งฟรี', PROFIT_FLOOR_APPLIED: 'กำไรขั้นต่ำทั้งงานทำให้ราคาสูงกว่าผลจากสูตร', SOURCE_EVIDENCE_LIMITED: 'หลักฐานของนโยบายบางรายการยังมีข้อจำกัด โปรดตรวจที่มาในแท็บตัวแปร', DEADLINE_RISK: 'ระยะเวลาสูงสุดเกินกำหนดส่งที่ระบุ' }
export function PricingResults({ preview }) {
  const rows = [['unitLandedCostSatang', 'ต้นทุนถึงไทยต่อชิ้น'], ['unitPriceSatang', 'ราคาขายต่อชิ้น'], ['totalPriceSatang', 'ราคาขายรวม'], ['grossProfitSatang', 'กำไรขั้นต้นรวม']]
  const result = preview.result, comparison = preview.comparison?.result
  return <div className="space-y-4" data-testid="pricing-preview-result"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="pb-2 text-left font-semibold">ผลทดลองจากระบบ · บาท</caption><thead><tr><th className="p-2">รายการ</th><th className="p-2">รุ่นที่ใช้งาน</th><th className="p-2">รุ่นที่ทดลอง</th><th className="p-2">ส่วนต่าง</th></tr></thead><tbody>{rows.map(([key, label]) => <tr key={key} className="border-t border-[var(--border)]"><th className="p-2 font-normal">{label}</th><td className="p-2">{money(comparison?.[key])}</td><td className="p-2 font-semibold">{money(result[key])}</td><td className="p-2">{comparison?.[key] != null && result[key] != null ? money(Number(result[key]) - Number(comparison[key])) : '—'}</td></tr>)}</tbody></table></div><p className="text-xs text-muted">รุ่นสูตรต้นทาง: {result.ruleVersion || '—'} · รุ่นเครื่องคำนวณ: {result.evaluatorVersion || '—'}</p><p className="text-sm">ตัวกำหนดราคาขาย: {{ floor: 'กำไรขั้นต่ำ', formula: 'สูตรคำนวณ' }[result.priceDriver] || result.priceDriver || '—'}{!comparison && ' · ยังไม่มีรุ่นใช้งานสำหรับเปรียบเทียบ'}</p><details><summary className="cursor-pointer text-sm font-semibold">รายละเอียดต้นทุน → Ladder → Floor → ราคาสุดท้าย</summary><dl className="mt-2 grid gap-2 text-xs md:grid-cols-2">{Object.entries(flatten(result.breakdown || {})).map(([key, value]) => <div key={key}><dt>{BREAKDOWN_LABELS[key] || key}</dt><dd>{/satang/i.test(key) ? money(value) : String(value ?? '—')}</dd></div>)}</dl></details>{result.warnings?.length > 0 && <ul className="list-inside list-disc rounded-lg bg-amber-50 p-3 text-sm" aria-label="คำเตือนการคำนวณ">{result.warnings.map((warning, i) => <li key={i}>{typeof warning === 'string' ? warning : WARNING_LABELS[warning.code] || warning.message || warning.code}</li>)}</ul>}{preview.tiers?.length > 0 && <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="pb-2 text-left font-semibold">ราคาตามจำนวน · ใช้ข้อมูลต้นทุนชุดเดียวกัน</caption><thead><tr><th className="p-2">จำนวน</th><th className="p-2">เดิม/ชิ้น</th><th className="p-2">ใหม่/ชิ้น</th><th className="p-2">ส่วนต่าง/ชิ้น</th></tr></thead><tbody>{preview.tiers.map((tier) => <tr key={tier.quantity} className="border-t border-[var(--border)]"><td className="p-2">{tier.quantity}</td><td className="p-2">{money(tier.comparison?.result?.unitPriceSatang)}</td><td className="p-2">{money(tier.result.unitPriceSatang)}</td><td className="p-2">{money(tier.comparison?.deltaUnitPriceSatang)}</td></tr>)}</tbody></table></div>}</div>
}
