#!/usr/bin/env node
// Single-source kernel mirror (ADR draft SCM-EXTRACTION D3).
//
// The pure SCM domain code — the Pricing evaluator, the Procurement calculators
// and the Inventory movement rules — has exactly ONE hand-edited source during
// the transition: the files under apps/server/src that production runs today.
// This script generates the service's copy from them with a fixed, mechanical
// import rewrite (extensionless → `.js`, `@/…` aliases → relative paths) and
// nothing else. `--check` regenerates in memory and fails on any difference, so
// the two copies cannot drift: edit the source, run this script, commit both.
//
// When the SCM process becomes the only executor of a flow, ownership of these
// files moves here and the apps/server copy is deleted (never the reverse edit).
//
//   node scripts/sync-kernel.mjs           # write src/kernel/** + KERNEL-MANIFEST.json
//   node scripts/sync-kernel.mjs --check   # exit 1 on drift
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, posix, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const serviceRoot = resolve(here, '..')
const repoRoot = resolve(serviceRoot, '..', '..')
const serverSrc = join(repoRoot, 'apps', 'server', 'src')
const kernelRoot = join(serviceRoot, 'src', 'kernel')

/** source path (relative to apps/server/src) → kernel path (relative to src/kernel). */
export const KERNEL_FILES = Object.freeze({
  'lib/validation/enums.js': 'lib/enums.js',
  'modules/commerce/domain/pricing-formula.js': 'commerce/pricing-formula.js',
  'modules/commerce/domain/pricing-rules.js': 'commerce/pricing-rules.js',
  'modules/commerce/domain/pricing-source.js': 'commerce/pricing-source.js',
  'modules/commerce/domain/pricing-engine.js': 'commerce/pricing-engine.js',
  'modules/commerce/domain/pricing-catalog-projection.js': 'commerce/pricing-catalog-projection.js',
  'modules/commerce/domain/commerce.js': 'commerce/commerce.js',
  'modules/commerce/domain/billing.js': 'commerce/billing.js',
  'modules/procurement/domain/procurement.js': 'procurement/procurement.js',
  'modules/inventory/domain/inventory.js': 'inventory/inventory.js',
  'modules/inventory/domain/inventory-costing.js': 'inventory/inventory-costing.js',
  'modules/inventory/domain/inventory-governance.js': 'inventory/inventory-governance.js',
  'modules/inventory/domain/inventory-wip.js': 'inventory/inventory-wip.js',
  'modules/inventory/domain/inventory-stocktake.js': 'inventory/inventory-stocktake.js',
  'modules/inventory/domain/warehouse-location.js': 'inventory/warehouse-location.js',
  'modules/inventory/domain/catalog-intake.js': 'inventory/catalog-intake.js',
})

const sha256 = (text) => createHash('sha256').update(text).digest('hex')

function rewriteSpecifier(specifier, sourceRel, kernelRel) {
  let target
  if (specifier.startsWith('@/')) target = specifier.slice(2)
  else if (specifier.startsWith('./') || specifier.startsWith('../')) target = posix.normalize(posix.join(posix.dirname(sourceRel), specifier))
  else return specifier // bare package (zod, yaml, node:crypto) — resolved from the service's own lockfile
  const withExt = target.endsWith('.js') ? target : `${target}.js`
  const mapped = KERNEL_FILES[withExt]
  if (!mapped) throw new Error(`${sourceRel} imports ${specifier}, which is not in the kernel manifest — a kernel file may only import other kernel files or packages`)
  let relative = posix.relative(posix.dirname(kernelRel), mapped)
  if (!relative.startsWith('.')) relative = `./${relative}`
  return relative
}

export function transform(text, sourceRel, kernelRel) {
  return text.replace(/(\bfrom\s+|\bimport\s+)(['"])([^'"]+)\2/g, (match, lead, quote, specifier) => `${lead}${quote}${rewriteSpecifier(specifier, sourceRel, kernelRel)}${quote}`)
}

export function generate() {
  const files = []
  for (const [sourceRel, kernelRel] of Object.entries(KERNEL_FILES)) {
    const sourcePath = join(serverSrc, ...sourceRel.split('/'))
    if (!existsSync(sourcePath)) throw new Error(`kernel source missing: apps/server/src/${sourceRel}`)
    const source = readFileSync(sourcePath, 'utf8')
    const output = transform(source, sourceRel, kernelRel)
    files.push({ source: `apps/server/src/${sourceRel}`, kernel: `src/kernel/${kernelRel}`, sourceSha256: sha256(source), kernelSha256: sha256(output), output })
  }
  const manifest = {
    note: 'GENERATED by services/scm/scripts/sync-kernel.mjs — the apps/server files are the single hand-edited source; never edit src/kernel/** by hand.',
    files: files.map(({ output, ...entry }) => entry),
  }
  return { files, manifest: `${JSON.stringify(manifest, null, 2)}\n` }
}

function main() {
  const check = process.argv.includes('--check')
  const { files, manifest } = generate()
  const drift = []
  for (const file of files) {
    const path = join(serviceRoot, ...file.kernel.split('/'))
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (current === file.output) continue
    if (check) drift.push(file.kernel)
    else { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, file.output) }
  }
  const manifestPath = join(kernelRoot, 'KERNEL-MANIFEST.json')
  const currentManifest = existsSync(manifestPath) ? readFileSync(manifestPath, 'utf8') : null
  if (currentManifest !== manifest) {
    if (check) drift.push('src/kernel/KERNEL-MANIFEST.json')
    else writeFileSync(manifestPath, manifest)
  }
  if (check && drift.length) {
    process.stderr.write(`kernel drift — run node services/scm/scripts/sync-kernel.mjs:\n  ${drift.join('\n  ')}\n`)
    process.exit(1)
  }
  process.stdout.write(`${check ? 'kernel in sync' : 'kernel written'}: ${files.length} files\n`)
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
