#!/usr/bin/env node
// ADR-005 — mirror V1's markdown corpus into docs/v1-inherited/ as read-only
// evidence. Source is NEVER written to: `G:\zuri` is live production.
//
// Usage: node scripts/import-v1-docs.mjs [--source <path>] [--dry]

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync, mkdirSync, rmSync } from 'fs'
import { execFileSync } from 'child_process'
import path from 'path'
import { fileURLToPath } from 'url'
import { stripTrailingNulls, interiorNullCount } from './canonical-text.mjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
// ROOT is the repository root. Before the 2026-08-12 flatten the app lived in
// zuri-v2-lab/, so ROOT was that directory and the mirror was one level up; the
// flatten moved this file without dropping the `..`, which pointed DEST outside
// the repository entirely and made `npm run docs:import-v1` a no-op on the mirror.
const DEST = path.resolve(ROOT, 'docs', 'v1-inherited')
const argv = process.argv.slice(2)
const SOURCE = argv.includes('--source') ? argv[argv.indexOf('--source') + 1] : 'G:/zuri'
const DRY = argv.includes('--dry')

// Product knowledge comes across. V1's own working method does not (ADR-005 §D8),
// and neither do 43 MB of images and canvases.
const SKIP_DIRS = new Set(['node_modules', '.git', 'gks', 'templates', 'msp', '_outputs', 'temp'])
const TAKE_EXT = ['.md']
const EXTRA_FILES = ['id_standards.yaml']

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue
    const full = path.join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, out)
    else if (TAKE_EXT.some((e) => entry.endsWith(e))) out.push(full)
  }
  return out
}

function sourceCommit() {
  try {
    return execFileSync('git', ['-C', SOURCE, 'rev-parse', '--short', 'HEAD'], { encoding: 'utf8' }).trim()
  } catch {
    return 'unknown'
  }
}

const banner = (relPath, commit) => `<!-- ADR-005: imported from Zuri V1 — DO NOT EDIT THIS FILE -->
> **Inherited from Zuri V1 · read-only.**
> Source: \`${SOURCE}/${relPath}\` @ \`${commit}\` · imported ${new Date().toISOString().slice(0, 10)}
> This describes **V1 semantics**, where *tenant* means **one shop** — V2's scope
> chain (Portfolio → Tenant → Business → Workspace) is different. Corrections belong
> in a V2 document that cites this file, never in this file. Cite its ids with a
> \`V1-\` prefix (e.g. \`V1-ADR-060\`) so they cannot be confused with V2 ids.

`

const docsDir = path.join(SOURCE, 'docs')
if (!existsSync(docsDir)) {
  console.error(`Source docs not found: ${docsDir}`)
  process.exit(1)
}

const commit = sourceCommit()
const files = walk(docsDir)
const extras = EXTRA_FILES.map((f) => path.join(SOURCE, f)).filter((f) => existsSync(f))

if (DRY) {
  console.log(`would import ${files.length} md + ${extras.length} extra file(s) from ${SOURCE} @ ${commit}`)
  process.exit(0)
}

// Full replace: the mirror must equal the source at the recorded commit.
if (existsSync(DEST)) rmSync(DEST, { recursive: true })
mkdirSync(DEST, { recursive: true })

/**
 * The mirror is a faithful copy, so it inherits whatever V1 left in a file — and
 * V1's product/roadmap/timeline.md ends in 22 NUL bytes. Git scans the whole
 * buffer when guessing text vs binary, so that one run made a plain markdown file
 * the single tracked document git called binary. Trailing NULs are padding, not
 * content; dropping them changes nothing anyone reads. It is reported rather than
 * done silently, because the artifact belongs upstream and someone should know
 * the mirror is not byte-identical there.
 */
function sanitize(text, relPath) {
  const cleaned = stripTrailingNulls(text)
  const dropped = text.length - cleaned.length
  if (dropped) console.log(`  stripped ${dropped} trailing NUL byte(s) — upstream artifact in ${relPath}`)
  const interior = interiorNullCount(cleaned)
  if (interior) console.warn(`  WARNING: ${interior} NUL byte(s) inside ${relPath} — left in place, check the source`)
  return cleaned
}

let bytes = 0
for (const file of files) {
  const relPath = path.relative(SOURCE, file).split(path.sep).join('/')
  const target = path.join(DEST, path.relative(docsDir, file))
  mkdirSync(path.dirname(target), { recursive: true })
  const body = banner(relPath, commit) + sanitize(readFileSync(file, 'utf8'), relPath)
  writeFileSync(target, body)
  bytes += body.length
}
for (const file of extras) {
  const name = path.basename(file)
  const body =
    `# ADR-005: imported from Zuri V1 (${SOURCE}/${name} @ ${commit}) — DO NOT EDIT\n` +
    sanitize(readFileSync(file, 'utf8'), name)
  writeFileSync(path.join(DEST, name), body)
  bytes += body.length
}

const manifest = {
  importedBy: 'scripts/import-v1-docs.mjs (ADR-005)',
  source: SOURCE,
  sourceCommit: commit,
  importedAt: new Date().toISOString(),
  files: files.length + extras.length,
  bytes,
  readOnly: true,
  note: 'Mirror of V1 product documentation. Evidence, not authority. Re-sync before each module cutover; never edit in place.',
}
writeFileSync(path.join(DEST, 'MANIFEST.json'), JSON.stringify(manifest, null, 2) + '\n')

writeFileSync(
  path.join(DEST, 'README.md'),
  `# V1 Inherited Documentation (read-only)

Mirror of \`${SOURCE}/docs\` at commit \`${commit}\`, imported by
\`npm run docs:import-v1\` per [ADR-005](../ADR-005-V1-DOCUMENTATION-CORPUS.md).

**Rules**

1. **Never edit anything in this folder.** It is evidence of what V1 says. Write
   corrections in a V2 document that cites the inherited file.
2. **It describes V1 semantics** — "tenant" here means *one shop*. V2's scope chain
   is Portfolio → Tenant (isolation) → Business → Workspace → Project.
3. **Cite its ids with a \`V1-\` prefix** (\`V1-ADR-060\`, \`V1-FEAT-21\`, \`V1-CR-007\`).
   Filenames keep their original form so comments in lifted V1 code still resolve.
4. **It is evidence, not authority.** V2 documents win on disagreement; V1's code
   wins over V1's docs.
5. **Re-sync before each module cutover** (V1 moves ~213 commits/90 days). Drift is
   visible in \`MANIFEST.json\` → \`sourceCommit\`.

Mapping from these ids to V2 requirement ids is filled **per feature at lift time**
in \`../replacement/PARITY-INVENTORY.md\` — not upfront.
`
)

console.log(`imported ${manifest.files} files (${(bytes / 1024 / 1024).toFixed(1)} MB) from ${SOURCE} @ ${commit}`)
console.log(`→ ${path.relative(ROOT, DEST).split(path.sep).join('/')}`)
