-- @req FR-133, FR-134, FR-135, FR-136 — production PostgreSQL foundation for
-- Asset identity, intake, evidence metadata, procurement references, lots,
-- temporal responsibility/location/allocation and depreciation candidates.
-- @spec CR-016, ADR-055, ADR-057, SEC-023
-- @tested tests/unit/asset-production-activation-contract.test.js
--
-- Generated by Prisma migrate diff from the pre-Asset production schema to the
-- approved Asset foundation schema, then reviewed for the server-owned Supabase
-- lane. The migration is additive; Supabase owns the migration ledger.

BEGIN;

-- CreateTable
CREATE TABLE "RegisteredAsset" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "intakeId" TEXT,
    "lotId" TEXT,
    "assetCode" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "categoryCode" TEXT NOT NULL,
    "description" TEXT,
    "brand" TEXT,
    "model" TEXT,
    "serialNumber" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "condition" TEXT NOT NULL DEFAULT 'GOOD',
    "acquisitionAmount" TEXT,
    "currency" TEXT,
    "receivedOn" TIMESTAMP(3),
    "registeredAt" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "RegisteredAsset_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssetIntake" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "intakeCode" TEXT NOT NULL,
    "schemaVersion" TEXT NOT NULL,
    "sourceChannel" TEXT NOT NULL,
    "sourceCorrelationId" TEXT NOT NULL,
    "origin" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "pipelineRunId" TEXT,
    "submittedByPersonId" TEXT,
    "submittedAt" TIMESTAMP(3),
    "approvedByPersonId" TEXT,
    "approvedAt" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetIntake_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssetEvidence" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "intakeId" TEXT NOT NULL,
    "registeredAssetId" TEXT,
    "fileAssetId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "sha256" TEXT,
    "paymentReference" TEXT,
    "extractionJson" TEXT NOT NULL DEFAULT '{}',
    "reviewJson" TEXT NOT NULL DEFAULT '{}',
    "reviewedByPersonId" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetEvidence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssetProcurementRef" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "intakeId" TEXT NOT NULL,
    "registeredAssetId" TEXT,
    "type" TEXT NOT NULL,
    "system" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "lineValue" TEXT,
    "status" TEXT NOT NULL DEFAULT 'UNRESOLVED',
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetProcurementRef_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssetLot" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "lotCode" TEXT NOT NULL,
    "manufacturedOn" TIMESTAMP(3),
    "expiresOn" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetLot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssetResponsibility" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "registeredAssetId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "personId" TEXT NOT NULL,
    "orgUnitSystem" TEXT,
    "orgUnitRef" TEXT,
    "effectiveFrom" TIMESTAMP(3) NOT NULL,
    "effectiveTo" TIMESTAMP(3),
    "acknowledgedAt" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetResponsibility_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssetLocationHistory" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "registeredAssetId" TEXT NOT NULL,
    "branchId" TEXT,
    "locationCode" TEXT NOT NULL,
    "locationName" TEXT NOT NULL,
    "isPrimary" BOOLEAN NOT NULL DEFAULT true,
    "effectiveFrom" TIMESTAMP(3) NOT NULL,
    "effectiveTo" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetLocationHistory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssetProjectAllocation" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "registeredAssetId" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "workstreamId" TEXT,
    "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "exclusive" BOOLEAN NOT NULL DEFAULT true,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "effectiveFrom" TIMESTAMP(3) NOT NULL,
    "effectiveTo" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetProjectAllocation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssetDepreciationCandidate" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "intakeId" TEXT,
    "registeredAssetId" TEXT,
    "method" TEXT NOT NULL,
    "acquisitionAmount" TEXT NOT NULL,
    "residualValue" TEXT NOT NULL,
    "currency" TEXT NOT NULL,
    "usefulLifeMonths" INTEGER NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "calculationVersion" TEXT NOT NULL,
    "scheduleJson" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PREVIEW',
    "reviewedByPersonId" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetDepreciationCandidate_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "RegisteredAsset_intakeId_key" ON "RegisteredAsset"("intakeId");

-- CreateIndex
CREATE INDEX "RegisteredAsset_tenantId_businessId_status_idx" ON "RegisteredAsset"("tenantId", "businessId", "status");

-- CreateIndex
CREATE INDEX "RegisteredAsset_businessId_serialNumber_idx" ON "RegisteredAsset"("businessId", "serialNumber");

-- CreateIndex
CREATE INDEX "RegisteredAsset_lotId_idx" ON "RegisteredAsset"("lotId");

-- CreateIndex
CREATE UNIQUE INDEX "RegisteredAsset_businessId_assetCode_key" ON "RegisteredAsset"("businessId", "assetCode");

-- CreateIndex
CREATE INDEX "AssetIntake_tenantId_businessId_status_idx" ON "AssetIntake"("tenantId", "businessId", "status");

-- CreateIndex
CREATE INDEX "AssetIntake_pipelineRunId_idx" ON "AssetIntake"("pipelineRunId");

-- CreateIndex
CREATE UNIQUE INDEX "AssetIntake_businessId_intakeCode_key" ON "AssetIntake"("businessId", "intakeCode");

-- CreateIndex
CREATE UNIQUE INDEX "AssetIntake_businessId_sourceChannel_sourceCorrelationId_key" ON "AssetIntake"("businessId", "sourceChannel", "sourceCorrelationId");

-- CreateIndex
CREATE INDEX "AssetEvidence_tenantId_businessId_status_idx" ON "AssetEvidence"("tenantId", "businessId", "status");

-- CreateIndex
CREATE INDEX "AssetEvidence_registeredAssetId_idx" ON "AssetEvidence"("registeredAssetId");

-- CreateIndex
CREATE INDEX "AssetEvidence_businessId_sha256_idx" ON "AssetEvidence"("businessId", "sha256");

-- CreateIndex
CREATE INDEX "AssetEvidence_businessId_paymentReference_idx" ON "AssetEvidence"("businessId", "paymentReference");

-- CreateIndex
CREATE UNIQUE INDEX "AssetEvidence_intakeId_fileAssetId_role_key" ON "AssetEvidence"("intakeId", "fileAssetId", "role");

-- CreateIndex
CREATE INDEX "AssetProcurementRef_tenantId_businessId_type_idx" ON "AssetProcurementRef"("tenantId", "businessId", "type");

-- CreateIndex
CREATE INDEX "AssetProcurementRef_registeredAssetId_idx" ON "AssetProcurementRef"("registeredAssetId");

-- CreateIndex
CREATE UNIQUE INDEX "AssetProcurementRef_intakeId_type_system_value_lineValue_key" ON "AssetProcurementRef"("intakeId", "type", "system", "value", "lineValue");

-- CreateIndex
CREATE INDEX "AssetLot_tenantId_businessId_expiresOn_idx" ON "AssetLot"("tenantId", "businessId", "expiresOn");

-- CreateIndex
CREATE UNIQUE INDEX "AssetLot_businessId_lotCode_key" ON "AssetLot"("businessId", "lotCode");

-- CreateIndex
CREATE INDEX "AssetResponsibility_tenantId_businessId_role_idx" ON "AssetResponsibility"("tenantId", "businessId", "role");

-- CreateIndex
CREATE INDEX "AssetResponsibility_registeredAssetId_role_effectiveTo_idx" ON "AssetResponsibility"("registeredAssetId", "role", "effectiveTo");

-- CreateIndex
CREATE INDEX "AssetResponsibility_personId_effectiveTo_idx" ON "AssetResponsibility"("personId", "effectiveTo");

-- CreateIndex
CREATE INDEX "AssetLocationHistory_tenantId_businessId_effectiveTo_idx" ON "AssetLocationHistory"("tenantId", "businessId", "effectiveTo");

-- CreateIndex
CREATE INDEX "AssetLocationHistory_registeredAssetId_isPrimary_effectiveT_idx" ON "AssetLocationHistory"("registeredAssetId", "isPrimary", "effectiveTo");

-- CreateIndex
CREATE INDEX "AssetLocationHistory_branchId_idx" ON "AssetLocationHistory"("branchId");

-- CreateIndex
CREATE INDEX "AssetProjectAllocation_tenantId_businessId_status_idx" ON "AssetProjectAllocation"("tenantId", "businessId", "status");

-- CreateIndex
CREATE INDEX "AssetProjectAllocation_registeredAssetId_exclusive_effectiv_idx" ON "AssetProjectAllocation"("registeredAssetId", "exclusive", "effectiveTo");

-- CreateIndex
CREATE INDEX "AssetProjectAllocation_projectId_effectiveTo_idx" ON "AssetProjectAllocation"("projectId", "effectiveTo");

-- CreateIndex
CREATE INDEX "AssetProjectAllocation_workstreamId_idx" ON "AssetProjectAllocation"("workstreamId");

-- CreateIndex
CREATE INDEX "AssetDepreciationCandidate_tenantId_businessId_status_idx" ON "AssetDepreciationCandidate"("tenantId", "businessId", "status");

-- CreateIndex
CREATE INDEX "AssetDepreciationCandidate_intakeId_idx" ON "AssetDepreciationCandidate"("intakeId");

-- CreateIndex
CREATE INDEX "AssetDepreciationCandidate_registeredAssetId_idx" ON "AssetDepreciationCandidate"("registeredAssetId");

-- AddForeignKey
ALTER TABLE "RegisteredAsset" ADD CONSTRAINT "RegisteredAsset_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RegisteredAsset" ADD CONSTRAINT "RegisteredAsset_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RegisteredAsset" ADD CONSTRAINT "RegisteredAsset_intakeId_fkey" FOREIGN KEY ("intakeId") REFERENCES "AssetIntake"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RegisteredAsset" ADD CONSTRAINT "RegisteredAsset_lotId_fkey" FOREIGN KEY ("lotId") REFERENCES "AssetLot"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetIntake" ADD CONSTRAINT "AssetIntake_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetIntake" ADD CONSTRAINT "AssetIntake_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetEvidence" ADD CONSTRAINT "AssetEvidence_intakeId_fkey" FOREIGN KEY ("intakeId") REFERENCES "AssetIntake"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetEvidence" ADD CONSTRAINT "AssetEvidence_registeredAssetId_fkey" FOREIGN KEY ("registeredAssetId") REFERENCES "RegisteredAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetEvidence" ADD CONSTRAINT "AssetEvidence_fileAssetId_fkey" FOREIGN KEY ("fileAssetId") REFERENCES "FileAsset"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetProcurementRef" ADD CONSTRAINT "AssetProcurementRef_intakeId_fkey" FOREIGN KEY ("intakeId") REFERENCES "AssetIntake"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetProcurementRef" ADD CONSTRAINT "AssetProcurementRef_registeredAssetId_fkey" FOREIGN KEY ("registeredAssetId") REFERENCES "RegisteredAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetLot" ADD CONSTRAINT "AssetLot_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetLot" ADD CONSTRAINT "AssetLot_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetResponsibility" ADD CONSTRAINT "AssetResponsibility_registeredAssetId_fkey" FOREIGN KEY ("registeredAssetId") REFERENCES "RegisteredAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetResponsibility" ADD CONSTRAINT "AssetResponsibility_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetLocationHistory" ADD CONSTRAINT "AssetLocationHistory_registeredAssetId_fkey" FOREIGN KEY ("registeredAssetId") REFERENCES "RegisteredAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetLocationHistory" ADD CONSTRAINT "AssetLocationHistory_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetProjectAllocation" ADD CONSTRAINT "AssetProjectAllocation_registeredAssetId_fkey" FOREIGN KEY ("registeredAssetId") REFERENCES "RegisteredAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetProjectAllocation" ADD CONSTRAINT "AssetProjectAllocation_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetProjectAllocation" ADD CONSTRAINT "AssetProjectAllocation_workstreamId_fkey" FOREIGN KEY ("workstreamId") REFERENCES "Workstream"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetDepreciationCandidate" ADD CONSTRAINT "AssetDepreciationCandidate_intakeId_fkey" FOREIGN KEY ("intakeId") REFERENCES "AssetIntake"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssetDepreciationCandidate" ADD CONSTRAINT "AssetDepreciationCandidate_registeredAssetId_fkey" FOREIGN KEY ("registeredAssetId") REFERENCES "RegisteredAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- The hosted application uses the canonical least-privilege runtime role from
-- 20260822204604_canonical_iam_runtime_role_cutover.sql. Browser/Data API roles
-- and service_role do not receive direct table access.
ALTER TABLE "RegisteredAsset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RegisteredAsset" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AssetIntake" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetIntake" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AssetEvidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetEvidence" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AssetProcurementRef" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetProcurementRef" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AssetLot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetLot" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AssetResponsibility" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetResponsibility" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AssetLocationHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetLocationHistory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AssetProjectAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetProjectAllocation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AssetDepreciationCandidate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetDepreciationCandidate" FORCE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
  "RegisteredAsset",
  "AssetIntake",
  "AssetEvidence",
  "AssetProcurementRef",
  "AssetLot",
  "AssetResponsibility",
  "AssetLocationHistory",
  "AssetProjectAllocation",
  "AssetDepreciationCandidate"
TO zuri_app_runtime;

DO $$
DECLARE
  target text;
BEGIN
  FOREACH target IN ARRAY ARRAY[
    'RegisteredAsset',
    'AssetIntake',
    'AssetEvidence',
    'AssetProcurementRef',
    'AssetLot',
    'AssetResponsibility',
    'AssetLocationHistory',
    'AssetProjectAllocation',
    'AssetDepreciationCandidate'
  ] LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = target
        AND policyname = 'zuri_app_runtime_all'
    ) THEN
      EXECUTE format(
        'CREATE POLICY zuri_app_runtime_all ON %I FOR ALL TO zuri_app_runtime, zuri_web_login USING (true) WITH CHECK (true)',
        target
      );
    ELSIF NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = target
        AND policyname = 'zuri_app_runtime_all'
        AND roles @> ARRAY['zuri_app_runtime'::name, 'zuri_web_login'::name]
        AND cmd = '*'
        AND permissive
    ) THEN
      RAISE EXCEPTION 'ASSET_RUNTIME_POLICY_COLLISION: public.%', target;
    END IF;
  END LOOP;
END $$;

REVOKE ALL ON TABLE "RegisteredAsset" FROM public, anon, authenticated, service_role;
REVOKE ALL ON TABLE "AssetIntake" FROM public, anon, authenticated, service_role;
REVOKE ALL ON TABLE "AssetEvidence" FROM public, anon, authenticated, service_role;
REVOKE ALL ON TABLE "AssetProcurementRef" FROM public, anon, authenticated, service_role;
REVOKE ALL ON TABLE "AssetLot" FROM public, anon, authenticated, service_role;
REVOKE ALL ON TABLE "AssetResponsibility" FROM public, anon, authenticated, service_role;
REVOKE ALL ON TABLE "AssetLocationHistory" FROM public, anon, authenticated, service_role;
REVOKE ALL ON TABLE "AssetProjectAllocation" FROM public, anon, authenticated, service_role;
REVOKE ALL ON TABLE "AssetDepreciationCandidate" FROM public, anon, authenticated, service_role;

COMMIT;
