-- @req FR-137, FR-138, FR-139, FR-140 — production execution metadata and
-- private object-storage boundary for receipt/payment evidence intake.
-- @spec CR-016, ADR-056, ADR-057, SEC-023
-- @tested tests/unit/asset-production-activation-contract.test.js
--
-- Generated by Prisma migrate diff from the approved Asset foundation schema
-- to the evidence-execution schema. The bucket remains private and is consumed
-- only through the server-side storage adapter.

BEGIN;

-- AlterTable
ALTER TABLE "AssetIntake" ADD COLUMN     "normalizedEnvelopeJson" TEXT NOT NULL DEFAULT '{}',
ADD COLUMN     "payloadSha256" TEXT,
ADD COLUMN     "validatedAt" TIMESTAMP(3),
ADD COLUMN     "validationJson" TEXT NOT NULL DEFAULT '{}';

-- CreateIndex
CREATE INDEX "AssetIntake_businessId_payloadSha256_idx" ON "AssetIntake"("businessId", "payloadSha256");

-- Supabase Storage enforces the same 20 MiB and MIME boundary as the intake
-- API. service_role bypasses Storage RLS; no anon/authenticated object policy is
-- created for this bucket, and application responses retain opaque references.
INSERT INTO storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
VALUES (
  'asset-evidence',
  'asset-evidence',
  false,
  20971520,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'application/pdf']::text[]
)
ON CONFLICT (id) DO UPDATE
SET
  public = false,
  file_size_limit = 20971520,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

COMMIT;
