// Human views generated from the doc graph (ADR-025 rev 2): agents query the
// graph; people read projections of it. Both views carry blindness assertions
// in doc-preflight — a generated view is only trustworthy if a check proves it
// saw its inputs (.brain/rca/2026-08-16-code-doc-drift-stale-inventories.md).

// @spec docs/decisions/ADR-025-DOMAIN-DRIVEN-DOCS-ARCHITECTURE.md
// @tested tests/unit/doc-views.test.js

import { classifyRequirements } from './capability-registry.mjs'

const sourcePath = value => value?.replace(/^apps\/server\//, '')

const banner = (title, tagline) => `# ${title}

| Field | Value |
|-------|-------|
| **Status** | Auto-generated |
| **Generator** | \`scripts/doc-graph.mjs\` (via doc-views) |

> ${tagline}
> Never hand-edit — regenerate with \`npm run docs:graph\`.

`

/** One section per domain: the lane, what it owns, what lives in it. */
export function domainMap(nodes, edges) {
  const domains = nodes.filter((n) => n.type === 'domain').sort((a, b) => a.id.localeCompare(b.id))
  const sections = domains.map((d) => {
    const name = d.id.slice('domain:'.length)
    const routes = edges.filter((e) => e.type === 'owned_by' && e.to === d.id && e.from.startsWith('route:'))
    const api = routes.filter((r) => r.from.startsWith('route:api:')).length
    const pages = routes.filter((r) => r.from.startsWith('route:page:')).length
    const codeInLane = nodes.filter(
      (n) => n.type === 'code_file' && (d.modules || []).some((m) => sourcePath(n.path).startsWith(`src/modules/${m}/`)),
    )
    const frs = new Set()
    for (const c of codeInLane)
      for (const e of edges) if (e.from === c.id && e.type === 'implements') frs.add(e.to.slice('req:'.length))
    const models = d.owns_models || []
    return [
      `## ${name}`,
      '',
      `Charter: [${d.path}](${d.path.replace(/^docs\//, '')})`,
      '',
      '| | |',
      '|---|---|',
      `| Modules | ${(d.modules || []).map((m) => `\`src/modules/${m}\``).join(', ')} |`,
      `| Models owned | ${models.length ? models.join(', ') : '— (state lives outside the shared schema by design)'} |`,
      `| Routes owned | ${routes.length} (${api} api · ${pages} pages) |`,
      `| FRs implemented in lane | ${frs.size ? [...frs].sort().join(', ') : '—'} |`,
      '',
    ].join('\n')
  })
  return (
    banner(
      'Domain Map',
      'One section per domain: the lane, what it owns, and what lives in it — generated from the charters and the graph (ADR-025).',
    ) +
    '> Machine-readable implementation readiness: [docs/.domain-state.json](.domain-state.json). It is generated with the graph and is not a runtime domain state.\n\n' +
    // DOMAIN-MAP is inlined into llms-full.txt, and a reader who lands on it directly
    // has no other path to the corpus: a hand-written pointer would be overwritten by
    // the next `docs:graph`, so the generator emits it.
    '> For LLM readers: [llms.txt](../llms.txt) is the repository index, and [llms-full.txt](../llms-full.txt) inlines this map, the working rules and every domain charter into one file (generated by `npm run docs:llms`).\n\n' +
    sections.join('\n')
  )
}

/** The full chain per FR: surface → code → rules → tests → feature. */
export function traceView(nodes, edges, inventory = []) {
  const classification = new Map(classifyRequirements(nodes, edges).map(row => [row.id, row.classification]))
  const featsByFr = new Map()
  for (const f of nodes.filter((n) => n.type === 'feature')) {
    for (const e of edges) {
      if (e.from === f.id && e.type === 'bundles') {
        const fr = e.to.slice('req:'.length)
        if (!featsByFr.has(fr)) featsByFr.set(fr, [])
        featsByFr.get(fr).push(`${f.id.slice('feat:'.length)} — ${f.label}`)
      }
    }
  }
  const routeByPath = new Map(nodes.filter((n) => n.type === 'route').map((n) => [sourcePath(n.path), n]))
  const byId = new Map(nodes.map((n) => [n.id, n]))
  const frs = nodes
    .filter((n) => n.type === 'requirement' && n.family === 'FR')
    .sort((a, b) => a.id.localeCompare(b.id))
  const blocks = frs.map((r) => {
    const fid = r.id.slice('req:'.length)
    const code = edges.filter((e) => e.to === r.id && e.type === 'implements').map((e) => e.from.slice('code:'.length))
    const tests = [...new Set(edges.filter((e) => e.to === r.id && e.type === 'verifies').map((e) => e.from.slice('test:'.length)))]
    const routes = code.map((c) => routeByPath.get(c)).filter(Boolean)
    const specs = new Set()
    for (const c of code) for (const s of byId.get(`code:${c}`)?.annotations?.['@spec'] || []) specs.add(s)
    const lines = [`### ${fid} — ${r.label}`, '']
    lines.push(`- **Classification:** ${classification.get(fid)}`)
    const feats = featsByFr.get(fid)
    if (feats) lines.push(`- **Feature:** ${feats.join(' · ')}`)
    lines.push(`- **Status:** ${r.declared}`)
    if (routes.length) lines.push(`- **Surface:** ${routes.map((rt) => `\`${rt.route}\` (${rt.kind})`).join(' · ')}`)
    lines.push(`- **Code:** ${code.length ? code.map((c) => `\`${c}\``).join(' · ') : '—'}`)
    lines.push(`- **Follows:** ${specs.size ? [...specs].sort().join(', ') : '—'}`)
    lines.push(`- **Tests:** ${tests.length ? tests.map((t) => `\`${t}\``).join(' · ') : '—'}`)
    lines.push('')
    return lines.join('\n')
  })
  return (
    banner(
      'Trace',
      'The full chain per functional requirement: which surface renders it, which code implements it, which rules it follows, which tests prove it, which feature bundles it.',
    ) + (inventory.length ? [
      '## Functional Requirement inventory', '',
      'Ownership names the domain of a canonical FR note; undeclared ownership stays UNKNOWN.',
      'Implementation lanes come from charter-scoped code evidence. Neither is inferred from the readiness primary domain.',
      'Bundled FR metadata/use cases are supplied by the named FEAT readiness item; standalone rows require their own FR entry.',
      'Evidence state describes code/test trace links, not a test execution or production claim.', '',
      '| FR | Classification | Feature bundle | Owning domain (note) | Implementation lanes | Readiness item | Primary domain | Metadata | Use case | Evidence state | Code | Tests |',
      '|---|---|---|---|---|---|---|---|---|---|---|---|',
      ...inventory.map(r => `| ${r.id} | ${r.classification} | ${r.featureId || '—'} | ${r.owningDomains.join(', ') || 'UNKNOWN'} | ${r.implementationDomains.join(', ') || '—'} | ${r.readinessId || '—'} | ${r.primaryDomain || '—'} | ${r.metadataPresent ? 'yes' : 'no'} | ${r.useCasePresent ? 'yes' : 'no'} | ${r.evidenceState} | ${r.codeCount} | ${r.testCount} |`), '', '',
    ].join('\n') : '') + blocks.join('\n')
  )
}
